package com.bittr.android.core.wallet.ldk.seed

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The only place in the codebase that names a Keystore key parameter.
 *
 * ## Rule 2: the key is non-auth-bound, and that is the faithful port
 *
 * Neither `setUserAuthenticationRequired(true)` nor
 * `setUnlockedDeviceRequired(true)` is set, and neither may be added. This looks
 * like a weakening and is not: the mnemonic's actual iOS class is
 * `afterFirstUnlockThisDeviceOnly` (`CacheManager.swift:358`, re-applied `:475`),
 * *not* `WhenUnlocked` — `WhenUnlocked` is the PIN's class. Two seed reads that
 * exist in the shipping iOS app today happen with no PIN and no biometric:
 * `CoreViewController.swift:229` (launch after 10 failed PIN attempts) and
 * `ResetApp.swift:131` (remove wallet without signing in). An auth-bound key
 * breaks exactly those, and the second one is the no-PIN wallet-removal path.
 *
 * It is also why the documented Keystore lock-screen invalidation does not apply
 * here: that invalidation is a property of auth-bound keys.
 *
 * If a future change wants an auth-bound key, the no-PIN removal path has to be
 * re-designed first, and BIT-8 re-opened. Not a judgement call in code.
 * `KeystoreKeySpecTest` reads `KeyInfo` back on-device and asserts both flags are
 * false; `KeystoreKeySpecGuardTest` fails the JVM build if either symbol appears
 * anywhere in the wallet modules.
 *
 * ## Rule 5: no PIN anywhere in this file
 *
 * The wrapping key is generated by the Keystore. The PIN is a salted-SHA-256
 * verifier (`CacheManager.swift:397`) and is never an input to key derivation —
 * a 4-6 digit PIN is a verifier, not key material. Note the signatures below take
 * no PIN parameter at all, which is what `PinIsNotKeyMaterialTest` checks: the
 * absence is structural rather than a convention someone has to remember.
 *
 * ## Why not `androidx.security:security-crypto`
 *
 * `EncryptedSharedPreferences` would hide precisely the parameters rules 2 and 5
 * are stated in terms of, behind a facade whose defaults are free to change
 * between versions. For the funds-bearing path we want the spec visible in the
 * diff.
 *
 * ## What we actually get, per API level
 *
 * See BIT-6 -> `seed-storage-security` §4 for the full table. The short version:
 * hardware backing is *observed* via `KeyInfo.getSecurityLevel()`, never
 * attested — key attestation produces a certificate chain for asymmetric keys,
 * and this key is symmetric, so the security level is a local self-report from
 * the same system an attacker would have compromised. Good enough to log per
 * device (`KeystoreSecurityLevelTest`); not a proof. On API 26-27 some devices
 * fall back to a software keystore with no API to require otherwise, so we do
 * not claim hardware backing there.
 *
 * None of this is what protects the funds. Under rule 1 the mnemonic is the root
 * of recovery and this blob is a cache (rule 3); Keystore strength governs how
 * hard the blob is to steal off a compromised device, never whether the user can
 * recover.
 */
class AndroidKeystoreSeedWrapper(
    private val alias: String = DEFAULT_ALIAS,
) : SeedWrapper {

    private val keyStore: KeyStore
        get() = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    override fun hasKey(): Boolean = keyStore.containsAlias(alias)

    override fun ensureKey() {
        if (hasKey()) return

        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            // Forces a fresh IV per encryption and refuses caller-supplied ones.
            // With GCM, IV reuse under the same key is catastrophic rather than
            // merely untidy, so this is left to the platform on purpose.
            .setRandomizedEncryptionRequired(true)
            // Deliberately NOT set, and enforced by the guards named above:
            //   .setUserAuthenticationRequired(true)
            //   .setUnlockedDeviceRequired(true)
            .build()

        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            .apply { init(spec) }
            .generateKey()
    }

    override fun wrap(plaintext: ByteArray): ByteArray {
        ensureKey()
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key()) }
        val ciphertext = cipher.doFinal(plaintext)
        // IV length is prefixed rather than assumed to be 12: GCM's default is 12
        // bytes today, and a blob written under one assumption and read under
        // another is undecryptable — which classifies as NoUsableMnemonic and
        // costs the user a restore. Cheap to make explicit.
        val iv = cipher.iv
        return ByteArray(1 + iv.size + ciphertext.size).also { out ->
            out[0] = iv.size.toByte()
            iv.copyInto(out, 1)
            ciphertext.copyInto(out, 1 + iv.size)
        }
    }

    override fun unwrap(ciphertext: ByteArray): ByteArray {
        require(ciphertext.isNotEmpty()) { "Empty seed blob" }
        val ivLength = ciphertext[0].toInt()
        require(ivLength in 1 until ciphertext.size) { "Malformed seed blob" }
        val iv = ciphertext.copyOfRange(1, 1 + ivLength)
        val body = ciphertext.copyOfRange(1 + ivLength, ciphertext.size)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(GCM_TAG_BITS, iv))
        }
        return cipher.doFinal(body)
    }

    override fun deleteKey() {
        keyStore.takeIf { it.containsAlias(alias) }?.deleteEntry(alias)
    }

    /**
     * @throws java.security.UnrecoverableKeyException when the alias is gone —
     * which [SeedBlobClassifier] reads as "no usable mnemonic", not as a failure.
     */
    private fun key(): SecretKey =
        keyStore.getKey(alias, null) as? SecretKey
            ?: throw java.security.UnrecoverableKeyException(
                "Keystore alias '$alias' is absent. The wrapped mnemonic is a cache (rule 3); " +
                    "this routes to restore-from-mnemonic, not to an error state.",
            )

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val DEFAULT_ALIAS = "com.bittr.android.wallet.seed.v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val GCM_TAG_BITS = 128
    }
}
