package com.bittr.android.core.wallet.ldk.seed

import android.os.Build
import android.security.keystore.KeyInfo
import android.security.keystore.KeyPermanentlyInvalidatedException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec

/**
 * The seed blob's authenticated encryption, under an AES-256/GCM key that never
 * leaves the Android Keystore.
 *
 * Written against `KeyGenParameterSpec` + `Cipher` directly, and **not** against
 * `androidx.security:security-crypto` / `EncryptedSharedPreferences`. That
 * library hides exactly the key parameters BIT-8 rules 2 and 5 are stated in
 * terms of, so a rule expressed as "no `setUserAuthenticationRequired(true)`"
 * would become unenforceable and untestable; its maintenance status is a second
 * reason not to put it on the funds-bearing path.
 *
 * Blob layout is `[iv-length: 1][iv][ciphertext||tag]`. The IV is generated by
 * the Keystore, not by us — see [WalletKeySpec.build] on
 * `setRandomizedEncryptionRequired`.
 */
class AndroidKeystoreBlobCodec(
    private val alias: String = WalletKeySpec.ALIAS,
) : BlobCodec {

    private val keyStore: KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    /**
     * Encrypt under the wallet key, replacing that key first if the platform
     * has invalidated it.
     *
     * The replacement is the part that matters, and leaving it out is a
     * plausible mistake with an ugly consequence. A
     * `KeyPermanentlyInvalidatedException` is raised at `Cipher.init`, on
     * *encrypt* as well as decrypt — so a stale alias makes the next `wrap`
     * fail too, and the restore path is a `wrap`. BIT-8 rule 3's routine case
     * ("the blob is gone, restore from the mnemonic") would become "cannot
     * restore": loss of access, which is exactly the failure
     * `seed-storage-security` §6.3 identifies in the literal iOS port and the
     * one this whole module is arranged to avoid.
     *
     * Deleting the alias loses nothing. The key's only job was to decrypt a
     * blob that, by the time we are here, has already been established as
     * unreadable.
     */
    override fun wrap(plaintext: ByteArray): ByteArray = try {
        encryptUnder(keyOrCreate())
            .let { it(plaintext) }
    } catch (_: KeyPermanentlyInvalidatedException) {
        deleteKey()
        encryptUnder(generateKey())(plaintext)
    }

    private fun encryptUnder(key: SecretKey): (ByteArray) -> ByteArray {
        val cipher = Cipher.getInstance(WalletKeySpec.TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv
        check(iv.size in 1..255) { "unexpected GCM IV length ${iv.size}" }
        return { plaintext -> byteArrayOf(iv.size.toByte()) + iv + cipher.doFinal(plaintext) }
    }

    override fun unwrap(blob: ByteArray): ByteArray {
        // A blob too short to carry its own IV cannot be authenticated, and
        // must not be reported as a transient failure: it is a lost cache, and
        // BIT-8 rule 3 says a lost cache routes to the restore screen.
        require(blob.isNotEmpty()) { "empty seed blob" }
        val ivLength = blob[0].toInt() and 0xff
        if (ivLength == 0 || blob.size <= 1 + ivLength) {
            throw javax.crypto.AEADBadTagException("seed blob is truncated")
        }
        val key = existingKey() ?: throw javax.crypto.AEADBadTagException(
            "no Keystore entry for $alias; the wrapped seed cannot be read",
        )
        val cipher = Cipher.getInstance(WalletKeySpec.TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            key,
            GCMParameterSpec(WalletKeySpec.GCM_TAG_LENGTH_BITS, blob, 1, ivLength),
        )
        return cipher.doFinal(blob, 1 + ivLength, blob.size - 1 - ivLength)
    }

    override fun deleteKey() {
        if (keyStore.containsAlias(alias)) keyStore.deleteEntry(alias)
    }

    /**
     * Where the key material actually sits, as reported by the platform.
     *
     * Recorded per device by `KeystoreSecurityLevelTest` into the BIT-18
     * matrix, and **not** asserted against a fixed value: API 26–27 devices
     * legitimately fall back to a software keystore and there is no API to
     * require otherwise.
     *
     * Honest about what this is worth: key attestation produces a certificate
     * chain for *asymmetric* keys only, so for a symmetric key this is a local
     * self-report from the same system an attacker would already have
     * subverted. Good enough to log per device; not a cryptographic proof. And
     * under BIT-8 rules 1 and 3 it is not what protects the funds — it governs
     * how hard the blob is to steal off a compromised device, never whether the
     * user can recover.
     */
    @Suppress("DEPRECATION")
    fun observedSecurityLevel(): String {
        val key = existingKey() ?: return "absent"
        val factory = SecretKeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE)
        val info = factory.getKeySpec(key, KeyInfo::class.java) as KeyInfo
        return when {
            Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> when (info.securityLevel) {
                KeyProperties_SECURITY_LEVEL_STRONGBOX -> "strongbox"
                KeyProperties_SECURITY_LEVEL_TRUSTED_ENVIRONMENT -> "trusted_environment"
                KeyProperties_SECURITY_LEVEL_SOFTWARE -> "software"
                else -> "unknown(${info.securityLevel})"
            }
            info.isInsideSecureHardware -> "secure_hardware"
            else -> "software"
        }
    }

    private fun keyOrCreate(): SecretKey = existingKey() ?: generateKey()

    private fun existingKey(): SecretKey? =
        (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.secretKey

    private fun generateKey(): SecretKey =
        KeyGenerator.getInstance("AES", ANDROID_KEYSTORE)
            .apply { init(WalletKeySpec.build(alias)) }
            .generateKey()

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"

        // KeyProperties.SECURITY_LEVEL_* are API 31+. Named as constants rather
        // than referenced so the module still compiles against a lower
        // compileSdk if it is ever lowered, and so the API-31 branch above
        // reads as one thing.
        const val KeyProperties_SECURITY_LEVEL_SOFTWARE = 0
        const val KeyProperties_SECURITY_LEVEL_TRUSTED_ENVIRONMENT = 1
        const val KeyProperties_SECURITY_LEVEL_STRONGBOX = 2
    }
}
