package com.bittr.android.core.wallet.ldk.seed

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties

/**
 * The Keystore parameters for the seed-wrapping key, in one place so a test can
 * read them without a device.
 *
 * **BIT-8 rule 2, and it is scope rather than preference: the key is
 * non-auth-bound.** No `setUserAuthenticationRequired(true)`, no
 * `setUnlockedDeviceRequired(true)`. This is the faithful port of the
 * mnemonic's actual iOS class, `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`
 * (`CacheManager.swift:358`, re-applied at `:475`) — *not* `WhenUnlocked`,
 * which is the PIN's class.
 *
 * The reason it cannot be quietly tightened "for safety": two unauthenticated
 * seed reads exist in the shipping iOS app today, and both are recovery paths.
 * `CoreViewController.swift:229` starts the wallet at launch after ten failed
 * PIN attempts, and `ResetApp.swift:131` removes the wallet without signing in.
 * Neither has a PIN or a biometric to offer. An auth-bound key would turn the
 * post-lockout removal path into "the app cannot be recovered" — which is why
 * BIT-8 rule 5 says that if an auth-bound key is ever reintroduced, the no-PIN
 * removal path has to be re-designed *first*.
 *
 * What we get in exchange is weaker than iOS in one specific way, and the
 * missing half is bought back in [com.bittr.android.core.wallet.ldk.state.WalletPaths]
 * rather than here: a non-auth-bound key is usable during Direct Boot, so the
 * blob lives in credential-encrypted storage, which is not readable until first
 * unlock after boot.
 *
 * Proved by `KeystoreKeySpecTest` (host-side, reads the spec back) and by the
 * instrumented `KeystoreKeyInfoTest` (on-device, reads `KeyInfo` back off a
 * generated key). The negative half — that nobody adds the banned flags later —
 * is `WalletKeystorePolicyGuardTest`.
 */
internal object WalletKeySpec {

    const val ALIAS = "com.bittr.android.wallet.seed.v1"

    /** AES-256/GCM with a 128-bit tag: the widest authenticated primitive the Keystore offers. */
    const val TRANSFORMATION = "AES/GCM/NoPadding"
    const val KEY_SIZE_BITS = 256
    const val GCM_TAG_LENGTH_BITS = 128

    fun build(alias: String = ALIAS): KeyGenParameterSpec =
        KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(KEY_SIZE_BITS)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            // A fresh IV per encryption, generated by the Keystore rather than
            // by us. GCM catastrophically fails on IV reuse, and this is the
            // setting that makes reuse unrepresentable instead of merely
            // unlikely. It is on by default; stated explicitly because a
            // default is not a decision anyone can point at in review.
            .setRandomizedEncryptionRequired(true)
            // Deliberately absent, and enforced by a source guard rather than a
            // comment:
            //   .setUserAuthenticationRequired(true)   <- breaks the no-PIN removal path
            //   .setUnlockedDeviceRequired(true)       <- breaks background node start
            .build()
}
