//
//  Language.swift
//  bittr
//
//  Created by Tom Melters on 07/10/2024.
//

import UIKit

class Language: NSObject {
    
    static func getWord(withID:String) -> String {
        
        if CacheManager.getLanguage() == "en_US" {
            return fromEnUS(withID: withID)
        } else {
            return ""
        }
    }
    
    static func fromEnUS(withID:String) -> String {
        
        let allWords:[String:String] = [
            "yourwallet": "your wallet",
            "syncing": "",
            "send": "Send",
            "receive": "Receive",
            "buy": "Buy",
            "totalprofit": "Total profit",
            "notransactions1": "There are no transactions. Tap ",
            "notransactions2": " to get your first bitcoin.",
            "transaction": "transaction",
            "instant": "Instant",
            "regular": "Regular",
            "amount": "Amount",
            "type": "Type",
            "id": "ID",
            "description": "Description",
            "currentvalue": "Current value",
            "purchasevalue": "Purchase value",
            "profit": "Profit",
            "addanote": "Add a note",
            "feespaid": "Fees paid",
            "confirmations": "Confirmations",
            "sats": "sats",
            "news": "news",
            "questions": "questions",
            "noarticles": "There are no articles.",
            "getsupport": "Get support",
            "restorewallet": "Restore wallet",
            "wipewallet": "Wipe wallet",
            "privacypolicy": "Privacy Policy",
            "termsandconditions": "Terms & Conditions",
            "currency": "Currency",
            "walletandbalance": "Wallet and balance",
            "devicedetails": "Device details",
            "devicedetails2": "device details",
            "appversion": "App version",
            "enteryourpincode": "Enter your PIN",
            "confirm": "Confirm",
            "setapin": "Set a PIN for secure access to your wallet",
            "confirmyourpin": "Confirm your PIN",
            "back": "Back",
            "next": "Next",
            "balance": "balance",
            "balance2": "Balance",
            "walletsubtitle": "These are the funds in your bitcoin wallet.",
            "lightningchannels": "lightning connections",
            "lightningexplanation1": "To send and receive instant bitcoin payments, you need to have at least one lightning connection connection.\n\nTo open a connection with bittr, buy bitcoin worth up to 100 CHF/EUR to receive a lightning connection. Check your wallet's Buy section or getbittr.com for all information.",
            "lightningchannel": "lightning connections",
            "sendbitcoin": "send bitcoin",
            "sendtoplabel": "Send bitcoin from your bitcoin wallet to another bitcoin wallet. Scan a QR code or input manually.",
            "sendtoplabellightning": "Send bitcoin from your bitcoin lightning wallet to another bitcoin lightning wallet.",
            "address": "Address",
            "invoice": "Invoice",
            "sendall": "Send all <amount> BTC",
            "youcansend": "You can send <amount> satoshis.",
            "enterinvoice": "Enter invoice",
            "enteraddress": "Enter address",
            "enteramount": "Enter amount",
            "manualinput": "Close camera",
            "confirmtransaction": "confirm transaction",
            "checkdetails": "Make sure these details are correct.",
            "feerate": "Select your preferred fee rate.",
            "edit": "Edit",
            "limitlightning": "why a limit for instant payments?",
            "limitlightninganswer": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning connection (for instant payments).\n\nIf you've received satoshis into your lightning connection, you can use those to pay lightning invoices.\n\nYou cannot make instant payments that exceed the funds in your lightning connection.",
            "checkyourconnection": "Check your connection",
            "trytoconnect": "You don't seem to be connected to the internet. Please try to connect.",
            "okay": "Okay",
            "receivebitcoin": "receive bitcoin",
            "thisisanaddress": "This is an address to your bitcoin wallet.",
            "createaninvoice": "Create a Lightning invoice to receive bitcoin instantly to your Lightning wallet.",
            "amountinsatoshis": "Amount (in satoshis)",
            "youcanreceive": "You can receive up to",
            "enterdescription": "Enter description",
            "createinvoice": "Create invoice",
            "lightninginvoice": "lightning invoice",
            "thisisyourinvoice": "This is your Lightning invoice.",
            "done": "Done",
            "copied": "Copied",
            "theresalimit": "There's a limit to the amount of satoshis you can receive per invoice.\n\nYour lightning connection has a size, ten times the amount of your first bittr purchase. If the size is 10,000 sats and you've already received 2,000 sats, you can still receive up to 8,000 sats in total.\n\nPer invoice you can receive up to ten percent of the connection size. If you need more, you can create multiple invoices.\n\nWhen the connection is full, we'll invite you to move your funds to your regular bitcoin wallet to make space for future transactions.",
            "oops": "Oops!",
            "addressfail": "We couldn't fetch a wallet address. Please try again.",
            "tryagain": "Try again",
            "addressfail2": "We couldn't fetch a wallet address",
            "pleasetryagain": "Please try again",
            "cancel": "Cancel",
            "unexpectederror": "Unexpected error",
            "error": "Error",
            "scanningnotsupported": "Scanning not supported",
            "scanningnotavailable": "Your device does not support scanning a code from an item. Please use a device with a camera.",
            "noaddressfound": "No address found.",
            "pleasescan": "Please scan a bitcoin or lightning address QR code or input the address manually.",
            "nobitcoinaddressfound": "No bitcoin address found.",
            "pleasescan2": "Please scan a bitcoin address QR code or input the address manually.",
            "spendablebalance": "Make sure the amount of BTC you wish to send is within your spendable balance.",
            "cannotproceed": "We couldn't proceed to the next step",
            "highfeerate": "High fee rate",
            "highfeerate2": "The fee you've selected costs more than 10 % of the bitcoin you're sending. Make sure this is as intended.",
            "youravailablebalance": "Your available balance",
            "isinsufficient": "is insufficient to cover this fee",
            "updateamount": "Update amount",
            "close": "Close",
            "lowfee": "Low fee",
            "lowfee2": "The fee you've selected is very low. Your transaction may take long to (or never) be confirmed.",
            "changefee": "Change fee",
            "continue": "Continue",
            "sendtransaction": "Send transaction",
            "sendconfirmation": "Are you sure you want to send <amount> BTC, with a fee of <fees> satoshis, to <address>?",
            "success": "Success",
            "success2": "success",
            "transactionsuccess": "Your transaction has been sent and will show up in your wallet shortly.",
            "transactionerror": "We're unable to complete your transaction. We're receiving the following error message",
            "transactionerror2": "We're unable to complete your transaction. Please close and reopen our app and try again.",
            "lightningconfirmation": "Are you sure you want to pay <amount> satoshis (<currency> <convertedamount>)?\n\nThis payment may incur fees of up to <fees> satoshis.",
            "paymentsuccessful": "Payment successful",
            "paymentfailed": "Payment failed",
            "paymentfailed2": "We were able to broadcast your payment, but it failed. <reason>.\n\nIf funds were recently deposited into your Lightning wallet, it may take some time for these to be confirmed and available for sending elsewhere.",
            "paymentfailed3": "Unable to send bitcoin payment. Please sync your wallet and try again.",
            "buybitcoin": "buy bitcoin",
            "buysubtitle": "To buy bitcoin, make a bank transfer to a partner and put your unique code in the transfer description field.",
            "buyempty": "No order has been set up. Tap below to create your first one.",
            "addanother": "add another",
            "youremail": "Your email",
            "youriban": "Your IBAN",
            "ouriban": "Partner IBAN",
            "ourname": "Partner",
            "yourcode": "Your code",
            "yourprofits": "your profits",
            "profitsubtitle": "Here's to financial independence! These are the results of your savings so far.",
            "totalinvestment": "Total investment",
            "finaldetails": "Finish",
            "bittrinstructions": "You can buy up to 999€ per 30 days from bittr. Purchases below 100€ go into your Lightning wallet, to save on transaction fees.",
            "bittrinstructions2": "We like dollar-cost-averaging. That's, for example, buying 50€ of bitcoin every Monday.",
            "bittrinstructions3": "Set up a recurring transfer to buy bitcoin repeatedly at a pace and amount that suits you.",
            "letsgo": "Let's go",
            "readyfortransfer": "We're ready for your transfer!",
            "personaldetails": "These are your personal details. To buy bitcoin, make a bank transfer at any time and include your unique code in the transfer description/memo field.",
            "screenshot": "Screenshot",
            "youvegotmail": "You've got mail! Please enter your verification code below.",
            "entercode": "Enter code",
            "resendcode": "Resend code",
            "bittrinstructions4": "Buy bitcoin whenever you want, simply by making a bank transfer.",
            "whatsyouriban": "What's your IBAN (International Bank Account Number)?",
            "whatsyouremail": "What's your email address?",
            "enteriban": "Enter IBAN",
            "enteremail": "Enter email",
            "verify": "Verify",
            "noiban": "I don't have an IBAN",
            "walletisready": "Your wallet is ready!",
            "firstbitcoin": "Get your first bitcoin, hassle-free, here with one of our partners.",
            "skip": "Skip",
            "incorrectpin": "Incorrect PIN",
            "repeatnumber": "Repeat the same number.",
            "confirmrecoveryphrase": "Enter these words to confirm your recovery phrase.",
            "enterword": "Enter word",
            "recoveryphrase": "This is your 12-word recovery phrase. It's crucial that you store it safely where no one can access it.",
            "recoveryphrase2": "This is your only opportunity to see it and save it.",
            "checkandconfirm": "Check and confirm that you understand the following details.",
            "checkandconfirm1": "With bitcoin, you are your own bank. No one else has access to your private keys.",
            "checkandconfirm2": "If you lose access to this app and your backup, your bitcoin cannot be recovered.",
            "iunderstand": "I understand",
            "welcome": "welcome!",
            "createyourownwallet": "Create your own bittr wallet and buy bitcoin directly from your banking app.",
            "createwallet": "Create wallet",
            "becareful": "Be careful!",
            "noscreenshot": "We'd highly recommend against screenshotting your recovery phrase.\n\nScreenshots can easily be accessed by others, who will have full access to your wallet.",
            "enterrecoveryphrase": "Enter your 12-word recovery phrase.",
            "accessdetails": "Access your device details in case you need our support.",
            "darkmode": "Dark mode",
            "devicetoken": "Device token",
            "fetch": "Fetch",
            "publickey": "Public key",
            "bittrpeer": "Bittr peer",
            "check": "Check",
            "bittrpurchases": "Bittr purchases",
            "bittrnotification": "Bittr notification",
            "retry": "Retry",
            "lightningchannels2": "Lightning connections",
            "cachedimages": "Cached images",
            "empty": "Empty",
            "goodjob": "Good job, you've just added new satoshis to your bitcoin piggy bank!",
            "newpayment": "You've received a new payment!",
            "fundingtx": "Channel funding transaction",
            "questionvc1": "There's a limit to the amount of satoshis you can receive per invoice.\n\nThe size of your bitcoin lightning connection is",
            "questionvc2": "satoshis. You've already received",
            "questionvc3": "sats, so you can still receive up to",
            "questionvc4": "sats in total.\n\nPer invoice you can receive up to ten percent of the connection size, so",
            "questionvc5": "sats. If you need more, you can create multiple invoices.\n\nWhen the connection is full, we'll invite you to move your funds to your regular bitcoin wallet to make space for future transactions",
            "questionvc6": "why can't I send instant payments?",
            "questionvc7": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning wallet (for instant payments).\n\nYou've already received",
            "questionvc8": "satoshis into your lightning wallet. Your lightning connection needs to contain a minimum of",
            "questionvc9": "sats, so the maximum amount you can send in total is",
            "questionvc10": "sats.\n\nPer invoice you can send up to ten percent of the connection size. The size of your connection is",
            "questionvc11": "sats, so per invoice you can send up to",
            "questionvc12": "why can't I receive instant payments?",
            "questionvc13": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning wallet (for instant payments).\n\nYou don't currently have a lightning connection.\n\nTo open a connection with bittr, buy bitcoin worth up to 100 CHF/EUR to receive a lightning connection. Check your wallet's Buy section or getbittr.com for all information.",
            "questionvc14": "satoshis through this lightning connection. The size of your connection is",
            "questionvc15": "sats, so you can still purchase another",
            "questionvc16": "sats.\n\nWhen the connection is full, we invite you to empty its funds into your bitcoin wallet so that you have space again.",
            "reserve": "reserve",
            "total": "total",
            "walletconnectfail": "Something went wrong starting your wallet. Please try again. If the issue persists, contact support@getbittr.com",
            "walletconnectfail2": "We couldn't load your new transactions. Please close and reopen this app to try again.",
            "bittrpayout": "Bittr payout",
            "newbittrpayment": "You're receiving a new payment! Tap Okay to receive it now and continue what you're doing after.",
            "receivingpayment": "receiving payment",
            "pleasesignin": "Please sign in and wait a moment to receive your payment.",
            "pleasesignintosend": "Please sign in to send this payment.",
            "couldntconnect": "We couldn't connect to bittr. Please try again.",
            "bittrpayoutfail": "The notification did not contain the data needed to complete your payout.",
            "closedlightningchannel": "closed lightning connection",
            "closedlightningchannel2": "Your lightning connection has been closed.<reason>\n\nAny funds that were in this connection are deposited into your bitcoin wallet.\n\nTo open a new connection with bittr, buy bitcoin worth up to 100 CHF/EUR. Check your wallet's Buy section or getbittr.com for all information.",
            "closedlightningchannel3": " We've been notified that ",
            "bittrnotificationfail": "Something went wrong processing the notification we sent to you. Please contact support@getbittr.com if you have any questions.",
            "pinlock": "You've entered an incorrect PIN too many times. Please restore your wallet.",
            "incorrectpin2": "Please enter your correct PIN. If you've forgotten it, please restore your wallet.",
            "restorewallet2": "\nThis app only supports one wallet simultaneously. Restoring a wallet means removing your current wallet from your device.\n\nOnly restore a wallet if you're sure you've properly backed up your wallet.",
            "restore": "Restore",
            "restorewallet3": "\nAre you sure you want to remove your wallet from this device and replace it with a restored one?",
            "restorewallet4": "Please close your lightning connection(s) before restoring a wallet.\n\nRestoring a wallet means removing your wallet from this device, upon which you may lose access to the funds in your lightning connection (if you don't close the connection first).",
            "closechannel": "Close connection(s)",
            "closechannel2": "If you close your lightning connection(s), its funds will be deposited back into your wallet.\n\nPlease wait for this transaction to show up, before definitively removing this wallet from your device.",
            "closechannel3": "Your lightning connection has been closed. Wait for any remaining funds to reappear in your wallet before removing this wallet from your device.",
            "closechannel4": "We could not close your lightning connection. Please try again.",
            "closechannel5": "Connection closure initiated. This may take several minutes to complete on the blockchain. You can now proceed with wallet reset.",
            "closechannel6": "Connection Closure Issue",
            "closechannel7": "The lightning connection could not be closed normally, possibly because the bittr node is offline or there's a connection issue.\n\nYou can close the connection unilaterally (force close), but this will require higher transaction fees and may take longer to complete.",
            "forceclose": "Force Close",
            "forceclose2": "Force closing the connection will require higher transaction fees but will work even if the bittr node is offline.",
            "restorewallet5": "Connection closure is in progress. You can proceed with wallet reset.",
            "pinlength": "PIN Length",
            "pincanbeupto8": "PIN can be up to 8 digits",
            "pinrequired": "PIN Required",
            "pinshouldbe4to8": "PIN should be between 4 and 8 digits",
            "syncingwallet": "Syncing wallet",
            "syncingwallet3": "syncing wallet",
            "syncingwallet2": "Please wait a moment while we're syncing your wallet.",
            "resendcode2": "Please wait 30 seconds before requesting another verification code.",
            "changeemail": "Change email",
            "conversionfail": "We're experiencing an issue fetching the latest conversion rates. Temporarily, our calculations - if available - won't reflect bitcoin's current value.",
            "unconfirmed": "Unconfirmed",
            "save": "Save",
            "lightningchannelfees": "lightning connection fees",
            "lightningchannelfees2": "This is your first instant bitcoin transaction.\n\nTo enable instant payments, we need to reserve funds in a lightning connection for you.\n\nThis fee covers both the capital we reserve (so you can make instant transactions) and the bitcoin network fees for opening and closing the connection.\n\nAll future instant bitcoin purchases will be completely free of network fees.",
            "copy": "Copy",
            "cachedimages1": "Are you sure you want to remove your cached images?",
            "remove": "Remove",
            "cacheemptied": "Cache emptied",
            "cachedimages2": "Any cached images have been removed.",
            "bittrpeer2": "You're connected to bittr.",
            "bittrpeer3": "You're not connected to bittr.",
            "connect": "Connect",
            "bittrtransactions": "Bittr transactions",
            "bittrtransactions2": "Would you like to fetch additional information about your bittr purchases?",
            "bittrtransactions3": "New information has been received. Your transactions have been refreshed.",
            "bittrtransactions4": "No new information is available.",
            "bittrnotification2": "There is no notification available for handling.",
            "bankingapp": "Open your banking app",
            "bankingapp2": "Create your (recurring) transfer to",
            "saved": "Saved",
            "screenshot2": "We've added the screenshot to your Photo Library.",
            "screenshot3": "We couldn't save your screenshot. Try taking a screenshot manually.",
            "receivenotifications": "Receive notifications",
            "receivenotifications2": "\nTo receive instant bitcoin payments, you must allow notifications.\n\nWithout notifications, you cannot receive payments to your wallet.",
            "verificationfail": "Please enter the correct verification code.",
            "bittrsignupfail": "Something went wrong creating your account. Please try again.",
            "bittrsignupfail2": "The IBAN you've entered appears to be invalid. Please enter a valid IBAN.",
            "bittrsignupfail3": "Something went wrong. Please try again later.",
            "bittrsignupfail4": "Something went wrong verifying your email address. Please try again.",
            "emailresent": "We've resent our email!",
            "emailresent2": "Check your Spam and Promotion folders to see if the code is there.\n\nPlease also check whether your address is correct:",
            "weresorry": "We're sorry!",
            "onlyiban": "Buying bitcoin with bittr is only available to IBAN holders.\n\nYou can still use your wallet to send and receive bitcoin.",
            "gotowallet": "Go to wallet",
            "fetchconversionrates": "fetch conversion rates",
            "startlightningnode": "start lightning node",
            "initiatewallet": "initiate wallet",
            "syncwallet": "sync wallet",
            "finalcalculations": "final calculations",
            "payrequest": "Pay request",
            "payrequest1": "You can pay between <minsendable> and <maxsendable> satoshis. How many satoshis would you like to pay?",
            "withdrawrequest": "Withdraw request",
            "withdrawrequest1": "You can withdraw between <minwithdrawable> and <maxwithdrawable> satoshis. How many satoshis would you like to withdraw?",
            "withdrawrequest3": "Are you sure you'd like to withdraw <withdrawable> satoshis?",
            "lnurlpayment": "Copy this invoice and go to Send to make your instant payment.",
            "lnurlfail1": "We could not complete this withdraw request. Error:",
            "lnurlfail2": "We could not complete your pay request. Error:",
            "lnurlscannerlabel": "Scan a QR code to perform an LNURL pay or withdraw request.",
            "lnurl": "LNURL status",
            "lnurlfail3": "We've received an error while handling this request. Please try again.",
            "lnurlfail4": "We currently only support LNURL pay and withdraw requests.",
            "sendvcscan": "Scan",
            "sendvcpaste": "Paste",
            "sendvctype": "Type",
            "language": "Language",
            "historicaldata": "We could not reach our server. Please try again.",
            "bitcoinvalue": "bitcoin value",
            "swapfunds": "swap funds",
            "swapfunds2": "Swap funds",
            "swapsubtitle": "Move your satoshis between your bitcoin wallet and your bitcoin lightning wallet.",
            "move": "Move",
            "onchaintolightning": "Onchain to Lightning",
            "lightningtoonchain": "Lightning to Onchain",
            "satsatatime": "Move <amount> sats at a time.",
            "enteramountofsatoshis": "Enter amount of satoshis",
            "nodatareceived": "No data was received",
            "swapamountexceeded": "You can only move up to <amount> satoshis at a time. Please enter an amount within this limit.",
            "swapfunds3": "The expected fee to move <amount> satoshis (<convertedamount>) is <feesamount> satoshis (<convertedfees>). Do you wish to proceed?",
            "proceed": "Proceed",
            "message": "message",
            "direction": "Direction",
            "fees": "Fees",
            "status": "Status",
            "swaperror1": "We could not initiate this swap.",
            "swaperror2": "We encountered some issue while processing your swap. No funds have been swapped. Please try again.",
            "swapstatuspreparing": "Preparing",
            "swapstatusawaitingconfirmation": "Waiting to be mined",
            "swapstatusawaitingpayment": "Awaiting payment",
            "swapstatusinvoicepending": "Awaiting swap payout",
            "swapstatusswapcomplete": "Swap complete",
            "swapstatusfailedtopay": "Swap failed (couldn't pay invoice)",
            "swapstatusexpired": "Swap expired",
            "swapstatusincorrectamount": "Swap failed (incorrect amount)",
            "swapstatusawaitingtransaction": "Awaiting transaction",
            "swapstatusinvoicexpired": "Swap failed (invoice expired)",
            "swapstatusfailed": "Swap failed",
            "both": "Both",
            "subtitleboth": "Share a single QR.",
            "bothamountlabel": "Amount and description (optional)",
            "add": "Add",
            "insatoshis": "In satoshis",
            "addressandamount": "Address and amount",
            "invoiceandamount": "Invoice and amount",
            "amountmissing": "Please enter the amount of satoshis you'd like to send.",
            "forgotpin": "Forgot PIN",
            "forgotpin2": "Please enter your 12-word recovery phrase to reset your PIN.",
            "forgotpin3": "The recovery phrase is incorrect.",
            "reset": "Reset",
            "resetpin": "Reset PIN",
            "newaddress": "new address",
            "newaddress2": "The current address is unused. Would you like to get a new one anyway?",
            "notificationsrequired": "Notifications Required",
            "notificationsrequiredmessage": "To process swaps, you need to be online. We'd like to notify you once your transaction is confirmed so that you can finalize the swap in the app. Please allow notification permissions.",
            "swapstatusupdate": "Your swap status has been updated",
            "invalidbitcoinaddress": "Invalid bitcoin address",
            "insufficientfunds": "Insufficient funds",
            "lightninginsufficientfunds": "You don't have enough instant bitcoin funds to send this payment. Your available balance is ",
            "onchaininsufficientfunds": "You don't have enough onchain funds to send this payment. Your available onchain balance is <amount> satoshis.",
            "swapinsufficientfunds": "However, you have enough regular bitcoin funds to swap and pay. Your available onchain balance is <amount> satoshis.",
            "swapinsufficientfundslightning": "However, you have enough instant bitcoin funds to swap and pay. Your available instant balance is <amount> satoshis.",
            "swapandpay": "Swap & Pay",
            "invalidinvoice": "Invalid Lightning invoice",
            "swapid": "Swap ID",
            "removewalletfromdevice": "Remove wallet",
            "removewallet1": "Are you sure you want to remove this wallet from your device?\n\nYou can restore the wallet using your recovery phrase.",
            "swapquestion": "Swap status",
            "swapquestionswapcreated0": "We've initiated the swap of your funds from onchain to lightning, but no funds have been moved yet.",
            "swapquestionswapcreated1": "We've initiated the swap of your funds from lightning to onchain, but no funds have been moved yet.",
            "swapquestiontransactionmempool0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nWe're currently waiting for your onchain transaction to be confirmed on the blockchain.",
            "swapquestiontransactionconfirmed0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning connection.",
            "swapquestioninvoicepending0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning connection.",
            "swapquestioninvoicefailedtopay0": "The swap of your funds from onchain to lightning could not be completed.\n\nIn order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has been paid and confirmed. However, the lightning invoice could not be paid. We're refunding the funds back into your onchain wallet.",
            "swapquestioncomplete0": "The swap of your funds from onchain to lightning has been completed.",
            "swapquestioncomplete1": "The swap of your funds from lightning to onchain has been completed.",
            "swapquestionexpired0": "The swap of your funds from onchain to lightning was not completed in time. If any funds were sent, they will be refunded into your onchain wallet.",
            "swapquestionexpired1": "The swap of your funds from lightning to onchain was not completed in time. If any funds were sent, they will be refunded into your lightning connection.",
            "swapquestiongeneric": "We're checking the current status of your swap.",
            "downloadswapfile": "Download details",
            "instantpayments": "Instant payments",
            "refundid": "Refund ID",
            "lightningid": "Lightning ID",
            "onchainid": "Onchain ID",
            "moved": "Moved",
            "from": "From",
            "swapstatus": "Swap status",
            "swapsucceeded": "Complete",
            "swappending": "Pending",
            "swapfailed": "Failed and refunded",
            "expecting": "Expecting",
            "note": "Note",
            "paymentrequestfailed": "Payment Request Failed",
            "paymentrequestfailed2": "We couldn't process this payment request. If this keeps happening, please contact support@getbittr.com.",
            "paymentrequest": "Payment Request",
            "paymentrequest2": "Someone wants to pay you <amount> satoshis! Please sign in to accept the payment.",
            "notification": "Notification",
            "notificationhandlingfail": "We cannot handle the notification you've received, because it doesn't contain the data we expect.",
            "recipientRejected": "Recipient rejected",
            "userAbandoned": "User abandoned",
            "retriesExhausted": "Retries exhausted",
            "paymentExpired": "Payment expired",
            "routeNotFound": "Route not found",
            "unknownRequiredFeatures": "Unknown required features",
            "invoiceRequestExpired": "Invoice request expired",
            "invoiceRequestRejected": "Invoice request rejected",
            "blindedPathCreationFailed": "Blinded path creation failed",
            "generatinginvoice": "Generating invoice",
            "missingwords": "Missing words",
            "missingwords2": "Please enter all 3 words to confirm your recovery phrase. This helps ensure you have backed up your wallet correctly.",
            "invalidwords": "Invalid words",
            "invalidwords2": "Some of the words you entered are not valid recovery phrase words. Please check your backup and try again.",
            "incorrectphrase": "Incorrect recovery phrase",
            "incorrectphrase2": "Some of the words you've entered are incorrect. Please double-check your recovery phrase backup and try again.\n\nFor your security, we recommend taking a fresh backup of your recovery phrase to ensure you have the correct words.",
            "incompletephrase": "Incomplete Recovery Phrase",
            "incompletephrase2": "Please enter all 12 words of your recovery phrase to restore your wallet.",
            "restorewalleterror": "Unable to restore wallet. Please try again.",
            "invalidphrase": "Invalid Recovery Phrase",
            "invalidphrase2": "The recovery phrase you entered is not valid. Please double-check your backup and try again.\n\nFor your security, we recommend taking a fresh backup of your recovery phrase to ensure you have the correct words.",
            "handlinglnurl": "Handling LNURL",
            "newlightningconnection": "New Lightning connection",
            "newlightningconnection2": "You've successfully opened a lightning connection with bittr. You can now send and receive payments across the bitcoin lightning network.\n\nAny funds that have already been deposited will show up shortly.",
            "channelfullswaprecommendation": "Bittr recommends you to swap <amount> satoshis. Alternatively you can get this transaction paid out to your regular balance. Would you like to receive this payment regularly (within 4-24 hours) or swap and receive instantly?",
            "swapandreceiveinstantly": "Swap & Instant Receive",
            "receiveonchain": "Receive on-chain",
            "counterpartyForceClosed": "the counterparty force closed the connection.",
            "holderForceClosed": "you force closed the connection.",
            "legacyCooperativeClosure": "the connection was closed cooperatively (legacy).",
            "counterpartyInitiatedCooperativeClosure": "the connection was closed cooperatively (counterparty-iniated).",
            "locallyInitiatedCooperativeClosure": "the connection was closed cooperatively (locally).",
            "commitmentTxConfirmed": "the commitment transaction was confirmed.",
            "fundingTimedOut": "the funding of the connection timed out.",
            "disconnectedPeer": "a peer connection could not be established.",
            "outdatedChannelManager": "the channel manager was outdated.",
            "counterpartyCoopClosedUnfundedChannel": "the unfunded connection was cooperatively closed (counterparty-initiated).",
            "fundingBatchClosure": "the funding batch was closed.",
            "htlCsTimedOut": "the hashed timelock contracts timed out.",
            "peerFeerateTooLow": "the proposed fee rate was too low.",
            "url": "URL",
            "transfer3Amount": "Amount",
            "transfer3AmountLabel": "You can buy up to 999 € worth of bitcoin per 30 days from bittr.",
            "transfer3Lightning": "Instant payments",
            "transfer3LightningLabel": "For purchases under 100 €, we create a lightning connection. With lightning, you can send and receive instant payments against low fees. The setup of the connection incurs a one-time fee of 10 000 satoshis.",
            "transfer3DCA": "Dollar-cost-averaging",
            "transfer3DCALabel": "Easily stack up on bitcoin by setting up a recurring bank transfer, e.g. 50 € every Monday."
            
        ]
        
        if let foundWord = allWords[withID] {
            return foundWord
        } else {
            return ""
        }
    }
    
}
