//
//  Language.swift
//  bittr
//
//  Created by Tom Melters on 07/10/2024.
//

import UIKit

class Language: NSObject {
    
    static func getWord(withID:String) -> String {
        
        if CacheManager.getLanguage() == "en_US" {
            return fromEnUS(withID: withID)
        } else {
            return ""
        }
    }
    
    static func fromEnUS(withID:String) -> String {
        
        let allWords:[String:String] = [
            "yourwallet": "your wallet",
            "syncing": "syncing",
            "send": "Send",
            "receive": "Receive",
            "buy": "Buy",
            "totalprofit": "Total profit",
            "notransactions1": "There are no transactions. Tap ",
            "notransactions2": " to get your first bitcoin.",
            "transaction": "transaction",
            "instant": "Instant",
            "regular": "Regular",
            "amount": "Amount",
            "type": "Type",
            "id": "ID",
            "description": "Description",
            "currentvalue": "Current value",
            "purchasevalue": "Purchase value",
            "profit": "Profit",
            "addanote": "Add a note",
            "feespaid": "Fees paid",
            "confirmations": "Confirmations",
            "sats": "sats",
            "news": "news",
            "questions": "questions",
            "noarticles": "There are no articles.",
            "getsupport": "Get support",
            "restorewallet": "Restore wallet",
            "privacypolicy": "Privacy Policy",
            "termsandconditions": "Terms & Conditions",
            "currency": "Currency",
            "walletandbalance": "Wallet and balance",
            "devicedetails": "Device details",
            "devicedetails2": "device details",
            "appversion": "App version",
            "enteryourpincode": "Enter your PIN code",
            "confirm": "Confirm",
            "setapin": "Set a PIN code for secure access to your wallet",
            "confirmyourpin": "Confirm your PIN code",
            "back": "Back",
            "next": "Next",
            "balance": "balance",
            "balance2": "Balance",
            "walletsubtitle": "These are the funds in your bitcoin wallet and bitcoin lightning channel.",
            "lightningchannels": "lightning channels",
            "lightningexplanation1": "To send and receive Bitcoin Lightning payments, you need to have at least one Lightning channel with anyone.\n\nTo open a channel with Bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "lightningchannel": "lightning channel",
            "sendbitcoin": "send bitcoin",
            "sendtoplabel": "Send bitcoin from your bitcoin wallet to another bitcoin wallet. Scan a QR code or input manually.",
            "sendtoplabellightning": "Send bitcoin from your bitcoin lightning wallet to another bitcoin lightning wallet.",
            "address": "Address",
            "invoice": "Invoice",
            "sendall": "Send all",
            "youcansend": "You can send",
            "enterinvoice": "Enter invoice",
            "enteraddress": "Enter address",
            "enteramount": "Enter amount",
            "manualinput": "Manual input",
            "confirmtransaction": "confirm transaction",
            "checkdetails": "Make sure these details are correct.",
            "feerate": "Select your preferred fee rate.",
            "edit": "Edit",
            "limitlightning": "why a limit for instant payments?",
            "limitlightninganswer": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nIf you've purchased satoshis into your lightning channel, you can use those to pay lightning invoices.\n\nYou cannot make instant payments that exceed the funds in your lightning channel.",
            "checkyourconnection": "Check your connection",
            "trytoconnect": "You don't seem to be connected to the internet. Please try to connect.",
            "okay": "Okay",
            "receivebitcoin": "receive bitcoin",
            "thisisanaddress": "This is an address to your bitcoin wallet.",
            "createaninvoice": "Create a Lightning invoice to receive bitcoin instantly to your Lightning wallet.",
            "amountinsatoshis": "Amount (in satoshis)",
            "youcanreceive": "You can receive up to",
            "enterdescription": "Enter description",
            "createinvoice": "Create invoice",
            "lightninginvoice": "lightning invoice",
            "thisisyourinvoice": "This is your Lightning invoice.",
            "done": "Done",
            "copied": "Copied",
            "theresalimit": "There's a limit to the amount of satoshis you can receive per invoice.\n\nYour bitcoin lightning channel has a size, ten times the amount of your first Bittr purchase. If the size is 10,000 sats and you've already purchased 2,000 sats, you can still receive up to 8,000 sats in total.\n\nPer invoice you can receive up to ten percent of the channel size. If you need more, you can create multiple invoices.\n\nWhen the channel is full, we empty the channel funds into your bitcoin wallet so that you have space again.",
            "oops": "Oops!",
            "addressfail": "We couldn't fetch a wallet address. Please try again.",
            "tryagain": "Try again",
            "addressfail2": "We couldn't fetch a wallet address",
            "pleasetryagain": "Please try again",
            "cancel": "Cancel",
            "unexpectederror": "Unexpected error",
            "error": "Error",
            "scanningnotsupported": "Scanning not supported",
            "scanningnotavailable": "Your device does not support scanning a code from an item. Please use a device with a camera.",
            "noaddressfound": "No address found.",
            "pleasescan": "Please scan a bitcoin or lightning address QR code or input the address manually.",
            "nobitcoinaddressfound": "No bitcoin address found.",
            "pleasescan2": "Please scan a bitcoin address QR code or input the address manually.",
            "spendablebalance": "Make sure the amount of BTC you wish to send is within your spendable balance.",
            "cannotproceed": "We couldn't proceed to the next step",
            "highfeerate": "High fee rate",
            "highfeerate2": "The fee you've selected costs more than 10 % of the bitcoin you're sending. Make sure this is as intended.",
            "youravailablebalance": "Your available balance",
            "isinsufficient": "is insufficient to cover this fee",
            "updateamount": "Update amount",
            "close": "Close",
            "lowfee": "Low fee",
            "lowfee2": "The fee you've selected is very low. Your transaction may take long to (or never) be confirmed.",
            "changefee": "Change fee",
            "continue": "Continue",
            "sendtransaction": "Send transaction",
            "sendconfirmation": "Are you sure you want to send",
            "sendconfirmation2": "with a fee of",
            "to": "to",
            "thisaddress": "this address",
            "success": "Success",
            "success2": "success",
            "transactionsuccess": "Your transaction has been sent and will show up in your wallet shortly.",
            "transactionerror": "We're unable to complete your transaction. We're receiving the following error message",
            "transactionerror2": "We're unable to complete your transaction. Please close and reopen our app and try again.",
            "lightningconfirmation": "Are you sure you want to pay",
            "lightningconfirmation2": "for this invoice",
            "paymentsuccessful": "Payment successful",
            "paymentfailed": "Payment failed",
            "paymentfailed2": "We were able to broadcast your payment, but it failed.\n\nIf funds were recently deposited into your Lightning wallet, it may take some time for these to be confirmed and available for sending elsewhere.",
            "buybitcoin": "buy bitcoin",
            "buysubtitle": "To buy bitcoin, make a transfer from your bank account to ours, with your unique code in the description.",
            "buyempty": "No transfer has been set up. Tap below to create your first one.",
            "addanother": "add another",
            "youremail": "Your email",
            "youriban": "Your IBAN",
            "ouriban": "Our IBAN",
            "ourname": "Our name",
            "yourcode": "Your code",
            "yourprofits": "your profits",
            "profitsubtitle": "Here's to financial independence! These are the results of your savings so far.",
            "totalinvestment": "Total investment",
            "finaldetails": "final details",
            "bittrinstructions": "You can buy up to 999€/day from bittr. Purchases below 100€ go into your Lightning wallet, to save on transaction fees.",
            "bittrinstructions2": "We like dollar-cost-averaging. That's, for example, buying 50€ of bitcoin every Monday.",
            "bittrinstructions3": "Set up a recurring transfer to buy bitcoin repeatedly at a pace and amount that suits you.",
            "letsgo": "Let's go",
            "readyfortransfer": "We're ready for your transfer!",
            "personaldetails": "These are your personal details. To buy bitcoin, make a transfer at any time with your unique code in the description.",
            "screenshot": "Take a screenshot",
            "youvegotmail": "You've got mail! Please enter your verification code below.",
            "entercode": "Enter code",
            "resendcode": "Resend code",
            "bittrinstructions4": "Buy bitcoin whenever you want, simply by making a bank transfer.",
            "whatsyouriban": "What's your IBAN (International Bank Account Number)?",
            "whatsyouremail": "What's your email address?",
            "enteriban": "Enter IBAN",
            "enteremail": "Enter email",
            "verify": "Verify",
            "noiban": "I don't have an IBAN",
            "walletisready": "Your wallet is ready!",
            "firstbitcoin": "Get your first bitcoin, hassle-free, here with one of our partners.",
            "skip": "Skip",
            "incorrectpin": "Incorrect PIN",
            "repeatnumber": "Repeat the same number.",
            "confirmrecoveryphrase": "Enter these words to confirm your recovery phrase.",
            "enterword": "Enter word",
            "recoveryphrase": "This is your 12-word recovery phrase. It's crucial that you store it safely where no one can access it.",
            "recoveryphrase2": "This is your only opportunity to see it and save it.",
            "checkandconfirm": "Check and confirm that you understand the following details.",
            "checkandconfirm1": "With bitcoin, you are your own bank. No one else has access to your private keys.",
            "checkandconfirm2": "If you lose access to this app and your backup, your bitcoin cannot be recovered.",
            "iunderstand": "I understand",
            "welcome": "welcome!",
            "createyourownwallet": "Create your own bittr wallet and buy bitcoin directly from your banking app.",
            "createwallet": "Create wallet",
            "becareful": "Be careful!",
            "noscreenshot": "We'd highly recommend against screenshotting your recovery phrase.\n\nScreenshots can easily be accessed by others, who will have full access to your wallet.",
            "enterrecoveryphrase": "Enter your 12-word recovery phrase.",
            "accessdetails": "Access your device details in case you need our support.",
            "darkmode": "Dark mode",
            "devicetoken": "Device token",
            "fetch": "Fetch",
            "publickey": "Public key",
            "bittrpeer": "Bittr peer",
            "check": "Check",
            "bittrpurchases": "Bittr purchases",
            "bittrnotification": "Bittr notification",
            "retry": "Retry",
            "lightningchannels2": "Lightning channels",
            "cachedimages": "Cached images",
            "empty": "Empty",
            "goodjob": "Good job, you've just put new satoshis in your bitcoin piggy bank via the Lightning Network!",
            "newpayment": "You've received a new payment!",
            "fundingtx": "Channel funding transaction",
            "questionvc1": "There's a limit to the amount of satoshis you can receive per invoice.\n\nThe size of your bitcoin lightning channel is",
            "questionvc2": "satoshis. You've already purchased",
            "questionvc3": "sats, so you can still receive up to",
            "questionvc4": "sats in total.\n\nPer invoice you can receive up to ten percent of the channel size, so",
            "questionvc5": "sats. If you need more, you can create multiple invoices.\n\nWhen the channel is full, we empty the channel funds into your bitcoin wallet so that you have space again",
            "questionvc6": "why can't I send instant payments?",
            "questionvc7": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nYou've already purchased",
            "questionvc8": "satoshis into your lightning channel. Your channel needs to contain a minimum of",
            "questionvc9": "sats, so the maximum amount you can send in total is",
            "questionvc10": "sats.\n\nPer invoice you can send up to ten percent of the channel size. The size of your channel is",
            "questionvc11": "sats, so per invoice you can send up to",
            "questionvc12": "why can't I receive instant payments?",
            "questionvc13": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nYou don't currently have a lightning channel.\n\nTo open a channel with Bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "questionvc14": "satoshis into your lightning channel. The size of your channel is",
            "questionvc15": "sats, so you can still purchase another",
            "questionvc16": "sats.\n\nWhen the channel is full, we empty its funds into your bitcoin wallet so that you have space again.",
            "reserve": "reserve",
            "total": "total",
            "walletconnectfail": "We can't connect to your wallet. Please try again or check your connection.",
            "bittrpayout": "Bittr payout",
            "newbittrpayment": "You're receiving a new Lightning payment! Tap Okay to receive it now and continue what you're doing after.",
            "receivingpayment": "receiving payment",
            "pleasesignin": "Please sign in and wait a moment to receive your Lightning payment.",
            "couldntconnect": "We couldn't connect to Bittr. Please try again.",
            "bittrpayoutfail": "The notification payload did not contain the data needed to complete your payout.",
            "closedlightningchannel": "closed lightning channel",
            "closedlightningchannel2": "We've been notified that your lightning channel has been closed.\n\nAny funds that were in this channel will be deposited into your bitcoin wallet.\n\nTo open a channel with Bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "bittrnotificationfail": "Something went wrong processing the notification we sent to you. Please reach out if you have any questions.",
            "pinlock": "You've entered an incorrect pin too many times. Please restore your wallet.",
            "incorrectpin2": "Please enter your correct pin. If you've forgotten it, please restore your wallet.",
            "restorewallet2": "\nThis app only supports one wallet simultaneously. Restoring a wallet means removing this current wallet from your device.\n\nOnly restore a wallet if you're sure you've properly backed up this current wallet.",
            "restore": "Restore",
            "restorewallet3": "\nAre you sure you want to remove this current wallet from your device and replace it with a restored one?\n\nIf you tap Restore, we'll reset and close the app. Please reopen it to proceed with your restoration.",
            "syncingwallet": "Syncing wallet",
            "syncingwallet3": "syncing wallet",
            "syncingwallet2": "Please wait a moment while we're syncing your wallet.",
            "resendcode2": "Please wait 30 seconds before requesting another verification code.",
            "changeemail": "Change email",
            "conversionfail": "We're experiencing an issue fetching the latest conversion rates. Temporarily, our calculations - if available - won't reflect bitcoin's current value.",
            "unconfirmed": "Unconfirmed",
            "save": "Save",
            "lightningchannelfees": "lightning channel fees",
            "lightningchannelfees2": "This is the first transaction of your new bitcoin lightning channel.\n\nThe opening and closing of a lightning channel incur mining fees, which we cover with a one-time upfront charge of 10 000 satoshis.\n\nAll additional transactions into and out of your lightning channel are free.",
            "copy": "Copy",
            "cachedimages1": "Are you sure you want to remove your cached images?",
            "remove": "Remove",
            "cacheemptied": "Cache emptied",
            "cachedimages2": "Any cached images have been removed.",
            "bittrpeer2": "You're connected to Bittr.",
            "bittrpeer3": "You're not connected to Bittr.",
            "connect": "Connect",
            "bittrtransactions": "Bittr transactions",
            "bittrtransactions2": "Would you like to fetch additional information about your Bittr purchases?",
            "bittrtransactions3": "New information has been received. Your transactions have been refreshed.",
            "bittrtransactions4": "No new information is available.",
            "bittrnotification2": "There is no notification available for handling.",
            "bankingapp": "Open your banking app",
            "bankingapp2": "Create your (recurring) transfer to",
            "saved": "Saved",
            "screenshot2": "We've added the screenshot to your Photo Library.",
            "screenshot3": "We couldn't save your screenshot. Try taking a screenshot manually.",
            "receivenotifications": "Receive notifications",
            "receivenotifications2": "\nTo send you bitcoin lightning payments, we need to notify you to open the Bittr app.\n\nPlease select your preference in the next alert.",
            "verificationfail": "Please enter the correct verification code.",
            "bittrsignupfail": "Something went wrong creating your account. Please try again.",
            "bittrsignupfail2": "The IBAN you've entered appears to be invalid. Please enter a valid IBAN.",
            "bittrsignupfail3": "Something went wrong. Please try again later.",
            "bittrsignupfail4": "Something went wrong verifying your email address. Please try again.",
            "emailresent": "We've resent our email!",
            "emailresent2": "Check your Spam and Promotion folders to see if the code is there.\n\nPlease also check whether your address is correct:",
            "weresorry": "We're sorry!",
            "onlyiban": "Buying bitcoin with bittr is only available to IBAN holders.\n\nYou can still use your wallet to send and receive bitcoin from other sellers.",
            "gotowallet": "Go to wallet",
            "fetchconversionrates": "fetch conversion rates",
            "startlightningnode": "start lightning node",
            "initiatewallet": "initiate wallet and blockchain",
            "syncwallet": "sync wallet",
            "finalcalculations": "final calculations",
            "payrequest": "Pay request",
            "payrequest1": "You can pay between",
            "payrequest2": "and",
            "payrequest3": "satoshis. How many satoshis would you like to pay?",
            "withdrawrequest": "Withdraw request",
            "withdrawrequest1": "You can withdraw between",
            "withdrawrequest2": "satoshis. How many satoshis would you like to withdraw?",
            "lnurlpayment": "Copy this invoice and go to Send to make your instant payment.",
            "lnurlfail1": "We could not complete this withdraw request. Error:",
            "lnurlscannerlabel": "Scan a QR code to perform an LNURL pay or withdraw request."
        ]
        
        if let foundWord = allWords[withID] {
            return foundWord
        } else {
            return ""
        }
    }
    
}
