//
//  Language.swift
//  bittr
//
//  Created by Tom Melters on 07/10/2024.
//

import UIKit

class Language: NSObject {
    
    static func getWord(withID:String) -> String {
        
        if CacheManager.getLanguage() == "en_US" {
            return fromEnUS(withID: withID)
        } else {
            return ""
        }
    }
    
    static func fromEnUS(withID:String) -> String {
        
        let allWords:[String:String] = [
            "yourwallet": "your wallet",
            "syncing": "",
            "send": "Send",
            "receive": "Receive",
            "buy": "Buy",
            "totalprofit": "Total profit",
            "notransactions1": "There are no transactions. Tap ",
            "notransactions2": " to get your first bitcoin.",
            "transaction": "transaction",
            "instant": "Instant",
            "regular": "Regular",
            "amount": "Amount",
            "type": "Type",
            "id": "ID",
            "description": "Description",
            "currentvalue": "Current value",
            "purchasevalue": "Purchase value",
            "profit": "Profit",
            "addanote": "Add a note",
            "feespaid": "Fees paid",
            "confirmations": "Confirmations",
            "sats": "sats",
            "news": "news",
            "questions": "questions",
            "noarticles": "There are no articles.",
            "getsupport": "Get support",
            "restorewallet": "Restore wallet",
            "wipewallet": "Wipe wallet",
            "privacypolicy": "Privacy Policy",
            "termsandconditions": "Terms & Conditions",
            "currency": "Currency",
            "walletandbalance": "Wallet and balance",
            "devicedetails": "Device details",
            "devicedetails2": "device details",
            "appversion": "App version",
            "enteryourpincode": "Enter your PIN",
            "confirm": "Confirm",
            "setapin": "Set a PIN for secure access to your wallet",
            "confirmyourpin": "Confirm your PIN",
            "back": "Back",
            "next": "Next",
            "balance": "balance",
            "balance2": "Balance",
            "walletsubtitle": "These are the funds in your bitcoin wallet and bitcoin lightning channel.",
            "lightningchannels": "lightning channels",
            "lightningexplanation1": "To send and receive Bitcoin Lightning payments, you need to have at least one Lightning channel with anyone.\n\nTo open a channel with Bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "lightningchannel": "lightning channel",
            "sendbitcoin": "send bitcoin",
            "sendtoplabel": "Send bitcoin from your bitcoin wallet to another bitcoin wallet. Scan a QR code or input manually.",
            "sendtoplabellightning": "Send bitcoin from your bitcoin lightning wallet to another bitcoin lightning wallet.",
            "address": "Address",
            "invoice": "Invoice",
            "sendall": "Send all",
            "youcansend": "You can send",
            "enterinvoice": "Enter invoice",
            "enteraddress": "Enter address",
            "enteramount": "Enter amount",
            "manualinput": "Close camera",
            "confirmtransaction": "confirm transaction",
            "checkdetails": "Make sure these details are correct.",
            "feerate": "Select your preferred fee rate.",
            "edit": "Edit",
            "limitlightning": "why a limit for instant payments?",
            "limitlightninganswer": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nIf you've purchased satoshis into your lightning channel, you can use those to pay lightning invoices.\n\nYou cannot make instant payments that exceed the funds in your lightning channel.",
            "checkyourconnection": "Check your connection",
            "trytoconnect": "You don't seem to be connected to the internet. Please try to connect.",
            "okay": "Okay",
            "receivebitcoin": "receive bitcoin",
            "thisisanaddress": "This is an address to your bitcoin wallet.",
            "createaninvoice": "Create a Lightning invoice to receive bitcoin instantly to your Lightning wallet.",
            "amountinsatoshis": "Amount (in satoshis)",
            "youcanreceive": "You can receive up to",
            "enterdescription": "Enter description",
            "createinvoice": "Create invoice",
            "lightninginvoice": "lightning invoice",
            "thisisyourinvoice": "This is your Lightning invoice.",
            "done": "Done",
            "copied": "Copied",
            "theresalimit": "There's a limit to the amount of satoshis you can receive per invoice.\n\nYour bitcoin lightning channel has a size, ten times the amount of your first Bittr purchase. If the size is 10,000 sats and you've already purchased 2,000 sats, you can still receive up to 8,000 sats in total.\n\nPer invoice you can receive up to ten percent of the channel size. If you need more, you can create multiple invoices.\n\nWhen the channel is full, we empty the channel funds into your bitcoin wallet so that you have space again.",
            "oops": "Oops!",
            "addressfail": "We couldn't fetch a wallet address. Please try again.",
            "tryagain": "Try again",
            "addressfail2": "We couldn't fetch a wallet address",
            "pleasetryagain": "Please try again",
            "cancel": "Cancel",
            "unexpectederror": "Unexpected error",
            "error": "Error",
            "scanningnotsupported": "Scanning not supported",
            "scanningnotavailable": "Your device does not support scanning a code from an item. Please use a device with a camera.",
            "noaddressfound": "No address found.",
            "pleasescan": "Please scan a bitcoin or lightning address QR code or input the address manually.",
            "nobitcoinaddressfound": "No bitcoin address found.",
            "pleasescan2": "Please scan a bitcoin address QR code or input the address manually.",
            "spendablebalance": "Make sure the amount of BTC you wish to send is within your spendable balance.",
            "cannotproceed": "We couldn't proceed to the next step",
            "highfeerate": "High fee rate",
            "highfeerate2": "The fee you've selected costs more than 10 % of the bitcoin you're sending. Make sure this is as intended.",
            "youravailablebalance": "Your available balance",
            "isinsufficient": "is insufficient to cover this fee",
            "updateamount": "Update amount",
            "close": "Close",
            "lowfee": "Low fee",
            "lowfee2": "The fee you've selected is very low. Your transaction may take long to (or never) be confirmed.",
            "changefee": "Change fee",
            "continue": "Continue",
            "sendtransaction": "Send transaction",
            "sendconfirmation": "Are you sure you want to send",
            "sendconfirmation2": "with a fee of",
            "to": "to",
            "thisaddress": "this address",
            "success": "Success",
            "success2": "success",
            "transactionsuccess": "Your transaction has been sent and will show up in your wallet shortly.",
            "transactionerror": "We're unable to complete your transaction. We're receiving the following error message",
            "transactionerror2": "We're unable to complete your transaction. Please close and reopen our app and try again.",
            "lightningconfirmation": "Are you sure you want to pay",
            "lightningconfirmation2": "for this invoice",
            "lightningconfirmation3": "This payment may incur fees of up to",
            "paymentsuccessful": "Payment successful",
            "paymentfailed": "Payment failed",
            "paymentfailed2": "We were able to broadcast your payment, but it failed.\n\nIf funds were recently deposited into your Lightning wallet, it may take some time for these to be confirmed and available for sending elsewhere.",
            "paymentfailed3": "Unable to send bitcoin payment. Please sync your wallet and try again.",
            "buybitcoin": "buy bitcoin",
            "buysubtitle": "To buy bitcoin, make a transfer from your bank account to ours, with your unique code in the description.",
            "buyempty": "No transfer has been set up. Tap below to create your first one.",
            "addanother": "add another",
            "youremail": "Your email",
            "youriban": "Your IBAN",
            "ouriban": "Our IBAN",
            "ourname": "Our name",
            "yourcode": "Your code",
            "yourprofits": "your profits",
            "profitsubtitle": "Here's to financial independence! These are the results of your savings so far.",
            "totalinvestment": "Total investment",
            "finaldetails": "final details",
            "bittrinstructions": "You can buy up to 999€ per 30 days from bittr. Purchases below 100€ go into your Lightning wallet, to save on transaction fees.",
            "bittrinstructions2": "We like dollar-cost-averaging. That's, for example, buying 50€ of bitcoin every Monday.",
            "bittrinstructions3": "Set up a recurring transfer to buy bitcoin repeatedly at a pace and amount that suits you.",
            "letsgo": "Let's go",
            "readyfortransfer": "We're ready for your transfer!",
            "personaldetails": "These are your personal details. To buy bitcoin, make a transfer at any time with your unique code in the description.",
            "screenshot": "Take a screenshot",
            "youvegotmail": "You've got mail! Please enter your verification code below.",
            "entercode": "Enter code",
            "resendcode": "Resend code",
            "bittrinstructions4": "Buy bitcoin whenever you want, simply by making a bank transfer.",
            "whatsyouriban": "What's your IBAN (International Bank Account Number)?",
            "whatsyouremail": "What's your email address?",
            "enteriban": "Enter IBAN",
            "enteremail": "Enter email",
            "verify": "Verify",
            "noiban": "I don't have an IBAN",
            "walletisready": "Your wallet is ready!",
            "firstbitcoin": "Get your first bitcoin, hassle-free, here with one of our partners.",
            "skip": "Skip",
            "incorrectpin": "Incorrect PIN",
            "repeatnumber": "Repeat the same number.",
            "confirmrecoveryphrase": "Enter these words to confirm your recovery phrase.",
            "enterword": "Enter word",
            "recoveryphrase": "This is your 12-word recovery phrase. It's crucial that you store it safely where no one can access it.",
            "recoveryphrase2": "This is your only opportunity to see it and save it.",
            "checkandconfirm": "Check and confirm that you understand the following details.",
            "checkandconfirm1": "With bitcoin, you are your own bank. No one else has access to your private keys.",
            "checkandconfirm2": "If you lose access to this app and your backup, your bitcoin cannot be recovered.",
            "iunderstand": "I understand",
            "welcome": "welcome!",
            "createyourownwallet": "Create your own bittr wallet and buy bitcoin directly from your banking app.",
            "createwallet": "Create wallet",
            "becareful": "Be careful!",
            "noscreenshot": "We'd highly recommend against screenshotting your recovery phrase.\n\nScreenshots can easily be accessed by others, who will have full access to your wallet.",
            "enterrecoveryphrase": "Enter your 12-word recovery phrase.",
            "accessdetails": "Access your device details in case you need our support.",
            "darkmode": "Dark mode",
            "devicetoken": "Device token",
            "fetch": "Fetch",
            "publickey": "Public key",
            "bittrpeer": "Bittr peer",
            "check": "Check",
            "bittrpurchases": "Bittr purchases",
            "bittrnotification": "Bittr notification",
            "retry": "Retry",
            "lightningchannels2": "Lightning channels",
            "cachedimages": "Cached images",
            "empty": "Empty",
            "goodjob": "Good job, you've just put new satoshis in your bitcoin piggy bank via the Lightning Network!",
            "newpayment": "You've received a new payment!",
            "fundingtx": "Channel funding transaction",
            "questionvc1": "There's a limit to the amount of satoshis you can receive per invoice.\n\nThe size of your bitcoin lightning channel is",
            "questionvc2": "satoshis. You've already purchased",
            "questionvc3": "sats, so you can still receive up to",
            "questionvc4": "sats in total.\n\nPer invoice you can receive up to ten percent of the channel size, so",
            "questionvc5": "sats. If you need more, you can create multiple invoices.\n\nWhen the channel is full, we empty the channel funds into your bitcoin wallet so that you have space again",
            "questionvc6": "why can't I send instant payments?",
            "questionvc7": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nYou've already purchased",
            "questionvc8": "satoshis into your lightning channel. Your channel needs to contain a minimum of",
            "questionvc9": "sats, so the maximum amount you can send in total is",
            "questionvc10": "sats.\n\nPer invoice you can send up to ten percent of the channel size. The size of your channel is",
            "questionvc11": "sats, so per invoice you can send up to",
            "questionvc12": "why can't I receive instant payments?",
            "questionvc13": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning channel (for instant payments).\n\nYou don't currently have a lightning channel.\n\nTo open a channel with Bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "questionvc14": "satoshis into your lightning channel. The size of your channel is",
            "questionvc15": "sats, so you can still purchase another",
            "questionvc16": "sats.\n\nWhen the channel is full, we empty its funds into your bitcoin wallet so that you have space again.",
            "reserve": "reserve",
            "total": "total",
            "walletconnectfail": "We can't connect to your wallet. Please try again or check your connection.",
            "walletconnectfail2": "We couldn't load your new transactions. Please close and reopen this app to try again.",
            "bittrpayout": "Bittr payout",
            "newbittrpayment": "You're receiving a new Lightning payment! Tap Okay to receive it now and continue what you're doing after.",
            "receivingpayment": "receiving payment",
            "pleasesignin": "Please sign in and wait a moment to receive your Lightning payment.",
            "couldntconnect": "We couldn't connect to Bittr. Please try again.",
            "bittrpayoutfail": "The notification payload did not contain the data needed to complete your payout.",
            "closedlightningchannel": "closed lightning channel",
            "closedlightningchannel2": "Your lightning channel has been closed.\n\nAny funds that were in this channel are deposited into your bitcoin wallet.\n\nTo open a channel with bittr, buy bitcoin worth up to 100 Swiss Francs or Euros. Check your wallet's Buy section or getbittr.com for all information.",
            "bittrnotificationfail": "Something went wrong processing the notification we sent to you. Please reach out if you have any questions.",
            "pinlock": "You've entered an incorrect PIN too many times. Please restore your wallet.",
            "incorrectpin2": "Please enter your correct PIN. If you've forgotten it, please restore your wallet.",
            "restorewallet2": "\nThis app only supports one wallet simultaneously. Restoring a wallet means removing this current wallet from your device.\n\nOnly restore a wallet if you're sure you've properly backed up this current wallet.",
            "restore": "Restore",
            "restorewallet3": "\nAre you sure you want to remove this current wallet from your device and replace it with a restored one?\n\nIf you tap Restore, we'll reset and close the app. Please reopen it to proceed with your restoration.",
            "restorewallet4": "Please close your Lightning channel before restoring a wallet.\n\nRestoring a wallet means removing this current wallet from your device, upon which you may lose access to the funds in your Lightning channel.",
            "closechannel": "Close channel",
            "closechannel2": "If you close your Lightning channel, its funds will be deposited back into your wallet. This is minus any transaction fees.\n\nPlease wait for this transaction to show up, before definitively removing this wallet from your device.",
            "closechannel3": "Your Lightning channel has been closed. Wait for any remaining funds to reappear in your wallet before removing this wallet from your device.",
            "closechannel4": "We could not close your Lightning channel. Please try again.",
            "closechannel5": "Channel closure initiated. This may take several minutes to complete on the blockchain. You can now proceed with wallet reset.",
            "closechannel6": "Channel Closure Issue",
            "closechannel7": "The Lightning channel could not be closed normally, possibly because the Bittr node is offline or there's a connection issue.\n\nYou can close the channel unilaterally (force close), but this will require higher transaction fees and may take longer to complete.",
            "forceclose": "Force Close",
            "forceclose2": "Force closing the channel will require higher transaction fees but will work even if the Bittr node is offline.",
            "restorewallet5": "Channel closure is in progress. You can proceed with wallet reset.",
            "pinlength": "PIN Length",
            "pincanbeupto8": "PIN can be up to 8 digits",
            "pinrequired": "PIN Required",
            "pinshouldbe4to8": "PIN should be between 4 and 8 digits",
            "syncingwallet": "Syncing wallet",
            "syncingwallet3": "syncing wallet",
            "syncingwallet2": "Please wait a moment while we're syncing your wallet.",
            "resendcode2": "Please wait 30 seconds before requesting another verification code.",
            "changeemail": "Change email",
            "conversionfail": "We're experiencing an issue fetching the latest conversion rates. Temporarily, our calculations - if available - won't reflect bitcoin's current value.",
            "unconfirmed": "Unconfirmed",
            "save": "Save",
            "lightningchannelfees": "lightning channel fees",
            "lightningchannelfees2": "This is the first transaction of your new bitcoin lightning channel.\n\nThe opening and closing of a lightning channel incur mining fees, which we cover with a one-time upfront charge of 10 000 satoshis.\n\nAll additional transactions into and out of your lightning channel are free.",
            "copy": "Copy",
            "cachedimages1": "Are you sure you want to remove your cached images?",
            "remove": "Remove",
            "cacheemptied": "Cache emptied",
            "cachedimages2": "Any cached images have been removed.",
            "bittrpeer2": "You're connected to Bittr.",
            "bittrpeer3": "You're not connected to Bittr.",
            "connect": "Connect",
            "bittrtransactions": "Bittr transactions",
            "bittrtransactions2": "Would you like to fetch additional information about your Bittr purchases?",
            "bittrtransactions3": "New information has been received. Your transactions have been refreshed.",
            "bittrtransactions4": "No new information is available.",
            "bittrnotification2": "There is no notification available for handling.",
            "bankingapp": "Open your banking app",
            "bankingapp2": "Create your (recurring) transfer to",
            "saved": "Saved",
            "screenshot2": "We've added the screenshot to your Photo Library.",
            "screenshot3": "We couldn't save your screenshot. Try taking a screenshot manually.",
            "receivenotifications": "Receive notifications",
            "receivenotifications2": "\nTo send you bitcoin lightning payments, we need to notify you to open the Bittr app.\n\nPlease select your preference in the next alert.",
            "verificationfail": "Please enter the correct verification code.",
            "bittrsignupfail": "Something went wrong creating your account. Please try again.",
            "bittrsignupfail2": "The IBAN you've entered appears to be invalid. Please enter a valid IBAN.",
            "bittrsignupfail3": "Something went wrong. Please try again later.",
            "bittrsignupfail4": "Something went wrong verifying your email address. Please try again.",
            "emailresent": "We've resent our email!",
            "emailresent2": "Check your Spam and Promotion folders to see if the code is there.\n\nPlease also check whether your address is correct:",
            "weresorry": "We're sorry!",
            "onlyiban": "Buying bitcoin with bittr is only available to IBAN holders.\n\nYou can still use your wallet to send and receive bitcoin from other sellers.",
            "gotowallet": "Go to wallet",
            "fetchconversionrates": "fetch conversion rates",
            "startlightningnode": "start lightning node",
            "initiatewallet": "initiate wallet and blockchain",
            "syncwallet": "sync wallet",
            "finalcalculations": "final calculations",
            "payrequest": "Pay request",
            "payrequest1": "You can pay between",
            "payrequest2": "and",
            "payrequest3": "satoshis. How many satoshis would you like to pay?",
            "withdrawrequest": "Withdraw request",
            "withdrawrequest1": "You can withdraw between",
            "withdrawrequest2": "satoshis. How many satoshis would you like to withdraw?",
            "withdrawrequest3": "Are you sure you'd like to withdraw",
            "lnurlpayment": "Copy this invoice and go to Send to make your instant payment.",
            "lnurlfail1": "We could not complete this withdraw request. Error:",
            "lnurlfail2": "We could not complete your pay request. Error:",
            "lnurlscannerlabel": "Scan a QR code to perform an LNURL pay or withdraw request.",
            "lnurl": "LNURL status",
            "lnurlfail3": "We received an error while handling this request. Please try again.",
            "lnurlfail4": "We currently only support LNURL pay and withdraw requests.",
            "sendvcscan": "Scan",
            "sendvcpaste": "Paste",
            "sendvctype": "Type",
            "language": "Language",
            "historicaldata": "We could not reach our API. Please try again.",
            "bitcoinvalue": "bitcoin value",
            "swapfunds": "swap funds",
            "swapfunds2": "Swap funds",
            "swapsubtitle": "Move your satoshis between your bitcoin wallet and your bitcoin lightning channel.",
            "move": "Move",
            "onchaintolightning": "Onchain to Lightning",
            "lightningtoonchain": "Lightning to Onchain",
            "satsatatime": "Move <amount> sats at a time.",
            "enteramountofsatoshis": "Enter amount of satoshis",
            "nodatareceived": "No data was received",
            "swapamountexceeded": "You can only move up to <amount> satoshis at a time. Please enter an amount within this limit.",
            "swapfunds3": "The expected fee to move <amount> satoshis (<convertedamount>) is <feesamount> satoshis (<convertedfees>). Do you wish to proceed?",
            "proceed": "Proceed",
            "message": "message",
            "direction": "Direction",
            "fees": "Fees",
            "status": "Status",
            "swaperror1": "We could not initiate this swap. We encountered a problem generating an invoice to pay out.",
            "swaperror2": "We encountered some issue while processing your swap. No funds have been swapped. Please try again.",
            "swapstatuspreparing": "Preparing",
            "swapstatusawaitingconfirmation": "Waiting to be mined",
            "swapstatusawaitingpayment": "Awaiting payment",
            "swapstatusinvoicepending": "Awaiting swap payout",
            "swapstatusswapcomplete": "Swap complete",
            "swapstatusfailedtopay": "Swap failed (couldn't pay invoice)",
            "swapstatusexpired": "Swap expired",
            "swapstatusincorrectamount": "Swap failed (incorrect amount)",
            "swapstatusawaitingtransaction": "Awaiting transaction",
            "swapstatusinvoicexpired": "Swap failed (invoice expired)",
            "swapstatusfailed": "Swap failed",
            "both": "Both",
            "subtitleboth": "Share a single QR.",
            "bothamountlabel": "Amount and description (optional)",
            "add": "Add",
            "insatoshis": "In satoshis",
            "addressandamount": "Address and amount",
            "invoiceandamount": "Invoice and amount",
            "amountmissing": "Please enter the amount of satoshis you'd like to send for this invoice.",
            "forgotpin": "Forgot PIN",
            "forgotpin2": "Please enter your 12-word recovery phrase to reset your PIN.",
            "forgotpin3": "The recovery phrase is incorrect.",
            "reset": "Reset",
            "resetpin": "Reset PIN",
            "newaddress": "new address",
            "newaddress2": "The current address is unused. Would you like to get a new one anyway?",
            "notificationsrequired": "Notifications Required",
            "notificationsrequiredmessage": "To process swaps, you need to be online and we have to wait for at least one confirmation on the blockchain. We'd like to notify you once your transaction confirms so that you can finalize the swap. Please allow notification permissions in Settings.",
            "swapstatusupdate": "Your swap status has been updated",
            "invalidbitcoinaddress": "Invalid Bitcoin address",
            "insufficientfunds": "Insufficient funds",
            "lightninginsufficientfunds": "You don't have enough Lightning balance to send this payment.",
            "onchaininsufficientfunds": "You don't have enough onchain balance to send this payment. Your available onchain balance is",
            "swapinsufficientfunds": "However, you have enough regular Bitcoin balance to swap and pay. Your available onchain balance is",
            "swapandpay": "Swap & Pay",
            "invalidinvoice": "Invalid Lightning invoice",
            "swapid": "Swap ID",
            "removewalletfromdevice": "Remove wallet",
            "removewallet1": "Are you sure you want to remove this wallet from your device?\n\nYou can restore the wallet using your recovery phrase.",
            "swapquestion": "Swap status",
            "swapquestionswapcreated0": "We've initiated the swap of your funds from onchain to lightning, but no funds have been moved yet.",
            "swapquestionswapcreated1": "We've initiated the swap of your funds from lightning to onchain, but no funds have been moved yet.",
            "swapquestiontransactionmempool0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning channel.\n\nWe're currently waiting for your onchain transaction to be confirmed on the blockchain.",
            "swapquestiontransactionconfirmed0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning channel.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning channel.",
            "swapquestioninvoicepending0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning channel.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning channel.",
            "swapquestioninvoicefailedtopay0": "The swap of your funds from onchain to lightning could not be completed.\n\nIn order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning channel.\n\nThe onchain transaction has been paid and confirmed. However, the lightning invoice could not be paid. We're refunding the funds back into your onchain wsllet.",
            "swapquestioncomplete0": "The swap of your funds from onchain to lightning has been completed.",
            "swapquestioncomplete1": "The swap of your funds from lightning to onchain has been completed.",
            "swapquestionexpired0": "The swap of your funds from onchain to lightning was not completed in time. If any funds were sent, they will be refunded into your onchain wallet.",
            "swapquestionexpired1": "The swap of your funds from lightning to onchain was not completed in time. If any funds were sent, they will be refunded into your lightning channel.",
            "swapquestiongeneric": "We're checking the current status of your swap."
        ]
        
        if let foundWord = allWords[withID] {
            return foundWord
        } else {
            return ""
        }
    }
    
}
