package com.bittr.android.core.wallet.ldk

/**
 * The K4 address golden: the first 20 signet receive and change addresses for
 * [Mnemonics.IOS_VECTOR].
 *
 * **Shared, for the same reason [Mnemonics] is.** `androidTest` cannot see
 * `test`, and these constants are the contract between the two halves of K4:
 * `Bip84AddressVectorTest` asserts bitcoin-kmp produces them on the JVM, and
 * `BdkAddressParityTest` asserts BDK produces them on a device. Copying them into
 * the instrumented source set would make that second test compare BDK against a
 * stale expectation of bitcoin-kmp — which is the failure mode a parity test
 * exists to catch, reintroduced by the fixture.
 *
 * **These are a golden, but not an unanchored one.** They were generated by
 * `Bip84Addresses` — but only after that implementation was checked against the
 * vectors BIP84 itself publishes, in the same test file that consumes them. A
 * golden produced by an unchecked implementation pins whatever that
 * implementation does, including a defect; these are pinned downstream of three
 * assertions against constants this repository did not author.
 *
 * Signet, because that is the chain the regtest build runs
 * (`Bip84Account.accountPath`). No mainnet key material: the mnemonic is the
 * public test vector already pinned in the iOS source.
 */
object Bip84AddressVectors {

    /** `m/84'/1'/0'/0/0` … `/0/19`. */
    val IOS_VECTOR_SIGNET_RECEIVE_20: List<String> = listOf(
        "tb1qc6p9hp4f7n6t6eadedu9ytzj4htmlty7zph2ja",
        "tb1q5u79z68h5laumjxn5hxt2ckqpj044cf2dwv8dq",
        "tb1qwelpzgh7pgpkdc6yqj835nrg25qe5y7tqpvn54",
        "tb1qkktmjfuqdgqk2sq7kzvudylewma7qmwggswdel",
        "tb1qxnzdzgpuf5qmcsf5my4y6zu3jmq3sxnagg0sr4",
        "tb1qct206ha779785rz06pr3m92dld7eqltgv56hs6",
        "tb1qw8a6n2zkcmru0hypz9xldg372u2tymjfk70g2k",
        "tb1qk75qnmx903x2uskeacf6z8mncwl6vtnghhutu7",
        "tb1qq4nd6vfpgv7l3t4gpvf9j5t95zaqglh9pyrqp9",
        "tb1qsvp5zyujumxr02g77ytuedhq44qxuynh3uskwm",
        "tb1q8amz20em9szfra0e7hj69z2fdhxtzuna4dwr0k",
        "tb1qkl33yr2q439rm4w2ms58cn9gqfeuxxuqwy6w92",
        "tb1qlmm2dsresy0fw0c9tvn6ele35pd27p8md6lcpl",
        "tb1qvcyxhg8tvd2zshj37a8260x8n6d24rcrh9utg0",
        "tb1q6tjsy8tw7ag8lyz656zpdecrglsyruprgxw83j",
        "tb1qvlx6rfvfhe8v5pql3afk2dufw4h6g4jyy3flxs",
        "tb1q3jd6pvlsnkk8xmc2vkeavytgddnsxhu9rgnxsu",
        "tb1q60g8l5y5c0rs0x9tn02rq88az7ffuun5f2jfra",
        "tb1qxma0zk6c7cc8vtrxc4mancpq9rw8w9utw4nt7v",
        "tb1qddfflzejmqjrq3vxesxkyp8mmuw2yezlle4eeh",
    )

    /** `m/84'/1'/0'/1/0` … `/1/19`. */
    val IOS_VECTOR_SIGNET_CHANGE_20: List<String> = listOf(
        "tb1qcqmsesrmltneuamf86r2gxrzkxc570mru2aek4",
        "tb1q8r8mlvjunjv5ysws9jjtjrpegxzur7q42wrx7e",
        "tb1qj7cut7nqup09ggn06pm4kkgnkuunscdu7vr802",
        "tb1q39sztmrcnyrx0z8c5f4usqpz29zv0pfcwwurep",
        "tb1q4vxyxk7fmze0992xl6hmfyjq09mcle976cs4lj",
        "tb1qtxrddf5enqkxw8pt48mayvzgxpdrry8dmj4rqs",
        "tb1qulmxjqs7y96y90ps5gyy04m05kqx6u0malmwcm",
        "tb1q4cxfw3fhlujyaxhlflusg9qrgjrrlxpkxzasg2",
        "tb1q0mrzty97eezdfjpedqh4j0wpj0qm53rgzvcye9",
        "tb1ql9guegk04kw30w50emyalh00zekpgjp4vr8myp",
        "tb1qj05vpmnlwmxgfpet3pvu900830z4snknas0ksp",
        "tb1q3sejjfffclz3av0kc49vqkuftgjv9c6zvuwxhy",
        "tb1qqv7cfpvtfsv3y09dq5x8ra85hqdwzhh53sy2h6",
        "tb1qdp80v7dx57t6nxvuze7hzt2uhwhjdr9xtuj4l5",
        "tb1qyu55gwdkz4wd3py7668l40mlrqtw8mpm8recwt",
        "tb1qy8680szeu6fd3ppnwkanh0g9kla9z4stml9ef7",
        "tb1qhag9dfys34akn3c4nyqyl9jrq2xd7t3kng67tz",
        "tb1qw2xzg86epv24amvjyhzcf7h8nc0avvplx6earw",
        "tb1qdlmjx9vnpq2ahsu6h3tgztzlzn6ndm3y69amsz",
        "tb1qn6cgstljr50t3jxrwvc7l9urf6kk40wncnk03y",
    )
}
