// AUTO-GENERATED by tools/academy_content.py. DO NOT EDIT.
// Source: ios/bittr/Academy/Academy/AcademyVC/Demo Data.swift

package com.bittr.android.feature.academy

/**
 * The Academy's lessons, transcribed from the iOS demo data.
 *
 * iOS builds this graph in `getDemoData()` and caches it on the Core view
 * controller under `downloadedAcademy`, behind a branch that would download it
 * instead if a backend existed (`AcademyViewController.swift:43-53`). It does not
 * yet, on either platform, so both ship the same constant — and it has to *be* the
 * same constant: lesson ids are the completion keys, so a divergence here would
 * mean a lesson completed on iOS reading as locked on Android for the same user.
 */
internal object AcademyContent {

    val levels: List<Level> = listOf(
        Level(
            order = 1,
            lessons = listOf(
                Lesson(
                    id = "whatisbitcoin",
                    title = "What is bitcoin?",
                    image = "whatisbitcoin",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin was introduced by <b>Satoshi Nakamoto</b> to create a new kind of digital money."),
                                Component.Text(text = "The idea was for people to send payments directly to each other without using a bank or other middleman."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Unlike fiat money, bitcoin isn’t controlled by any one group or government. It’s <b>decentralized</b> and follows strict rules that keep it running."),
                                Component.Text(text = "This means no one owns or can manipulate bitcoin on their own."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Just like other money, bitcoin can be used to pay for products and services."),
                                Component.Text(text = "To send bitcoin, all you need is the recipient’s address."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Transactions are stored in blocks on the <b>blockchain</b>; a public ledger everyone can see."),
                                Component.Text(text = "Transactions are usually confirmed within 10 minutes - significantly faster than traditional systems."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Supply is limited: only <b>21 million</b> bitcoin will ever exist. That makes it scarce and valuable."),
                                Component.Text(text = "New bitcoin gets <b>mined</b> through the process of helping add new transactions to the blockchain."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whataresatoshis",
                    title = "What are satoshis?",
                    image = "whataresatoshis",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "A bitcoin can be broken down into <b>100 million</b> units called <b>satoshis</b>."),
                                Component.Text(text = "They're named after bitcoin’s creator, Satoshi Nakamoto."),
                                Component.Text(text = "So 1 bitcoin equals 100,000,000 satoshis (or sats)."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "For a transaction of 0.000021453 bitcoin, we speak of 21,453 sats."),
                                Component.Text(text = "This makes bitcoin more practical for everyday use, like coffee purchases or online microtransactions."),
                                Component.Text(text = "With a bitcoin being worth over 100,000 €, the satoshi allows you to send or receive tiny amounts."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/22dd2c8de1aa8092b970daaebb69ad2d.png"),
                                Component.Text(text = "Satoshis are increasingly becoming the standard when speaking of bitcoin amounts. Thanks to their simplicity and intuitiveness."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "theproblemwithfiatcurrencies",
                    title = "The problem with fiat currencies",
                    image = "theproblemwithfiatcurrencies",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "A <b>fiat currency</b> is a type of money issued by a government, which isn't backed by a physical commodity like gold."),
                                Component.Text(text = "Its stability and value depend on the issuing government’s policies and the economy’s health."),
                                Component.Text(text = "Most widely used currencies today - like the Euro and USD - are forms of fiat currency."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "With fiat currency, governments can <b>influence economic activity</b> through monetary policies - like adjusting interest rates and setting reserve requirements for banks."),
                                Component.Text(text = "Governments can <b>print money</b> as needed - to fund new spending, manage debt, or respond to crises."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "A main characteristic is that fiat currencies tend toward <b>inflation</b>."),
                                Component.Text(text = "With governments printing more currency, the money devalues over time."),
                                Component.Text(text = "External events, like COVID-19, can cause high inflation rates. In extreme cases, fiat currencies can experience <b>hyperinflation</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Fiat currencies are easily portable, divisible, and widely accepted."),
                                Component.Text(text = "However, the legacy financial systems that underpin them, can create <b>slow processing times</b>, <b>limited availability</b> during weekends or holidays, and <b>chargeback risks</b> for merchants."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin is an alternative to fiat currency - retaining its useful properties while addressing its limitations."),
                                Component.Text(text = "It's <b>highly portable and divisible</b>. It has a <b>finite, predictable supply</b>, offering protection against inflation. Its value isn’t tied to the economic stability of any country."),
                                Component.Text(text = "Though, its utility as a payment method is still limited by factors such as a lack of merchant acceptance."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Here's a chart that compares bitcoin's characteristics to fiat currency and gold."),
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/1fbd2c8de1aa81a89978e610bbcdd8fd.webp"),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whydopeopleinvestinbitcoin",
                    title = "Why do people invest in bitcoin?",
                    image = "whydopeopleinvest",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin has grown from a niche idea into a <b>standalone asset class</b>."),
                                Component.Text(text = "Why do private investors, family offices, and institutions now look at bitcoin?"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>Diversification</b>"),
                                Component.Text(text = "Long-term data shows that bitcoin often moves differently from traditional assets."),
                                Component.Text(text = "That’s what many investors want - building blocks that don’t rise and fall at the same time."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>Preserving value long-term</b>"),
                                Component.Text(text = "Bitcoin's predictable scarcity protects against inflation. This makes it interesting for retirement and intergenerational wealth."),
                                Component.Text(text = "Bitcoin is volatile in the short term. The long-term case is measured in years and decades, not weeks."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>Future utility</b>"),
                                Component.Text(text = "As more infrastructure appears, practical use of bitcoin is growing. This gives more reasons to get in early."),
                                Component.Text(text = "You can transfer value without a middleman, globally, 24/7. And more lenders now accept bitcoin as collateral."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>Skepticism of centralized finance</b>"),
                                Component.Text(text = "Many investors want less dependency on third parties. With bitcoin, you hold your own keys and control your own coins."),
                                Component.Text(text = "Transactions are hard to block or reverse. And the decentralized, global system is much harder to compromise in hacking attempts."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin isn’t for everyone. If you need perfect peace of mind and hate price swings, keep the allocation small."),
                                Component.Text(text = "If you do invest, you’ll need a long time horizon, the ability to stay calm during drawdowns, and clear rules for security and risk management."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whyisbitcoinvolatile",
                    title = "Why is bitcoin volatile?",
                    image = "whyisbitcoinvolatile",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Volatility measures how much an asset’s price varies around its average over time."),
                                Component.Text(text = "Assets with frequent, significant price fluctuations are considered more volatile."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin has grown enormously over the years, but is also known for rapid price swings."),
                                Component.Text(text = "This volatility offers potential for impressive returns, but also poses risks associated with short-term price unpredictability."),
                                Component.Text(text = "What drives this volatility and what could it mean for bitcoin’s future?"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "As a relatively new asset, bitcoin’s markets react sharply to changes in demand."),
                                Component.Text(text = "The role bitcoin will ultimately play in the global financial system is still being defined."),
                                Component.Text(text = "Each new regulation, company adoption, or economic event can influence its perceived value."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "As a currency, bitcoin's value isn’t tied to any cash flows. Its price is based solely on demand."),
                                Component.Text(text = "For traditional assets, future cash flows offer a way to predict their value - creating a perception of stability."),
                                Component.Text(text = "Bitcoin’s value depends on its acceptance as part of the global economy, which is harder to model."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin’s market cap is around 2 trillion USD - a mere fraction of gold’s market cap."),
                                Component.Text(text = "As such, it takes less buying or selling power to move its price."),
                                Component.Text(text = "Additionally, some individuals hold large amounts. A single sale by one of these holders can create noticeable price changes."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Finally, unlike assets traded on major centralized exchanges, bitcoin liquidity is spread across many exchanges."),
                                Component.Text(text = "This leads to price differences and increased price sensitivity on individual platforms."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "As bitcoin matures, factors causing its volatility today may fade."),
                                Component.Text(text = "Regulatory clarity is likely to improve over time, reducing uncertainty. As bitcoin’s market cap grows, the impact of individual transactions decreases."),
                                Component.Text(text = "The development of a more efficient market will allow investors to trade with less price disruption."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whatismining",
                    title = "What is mining?",
                    image = "whatismining",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>Mining</b> is the process through which <b>new bitcoins</b> are generated and added to circulation."),
                                Component.Text(text = "It’s a digital competition where powerful computers work to <b>confirm bitcoin transactions</b>."),
                                Component.Text(text = "As miners commit resources (electricity, time, computing power), they make bitcoin highly <b>resistant to attacks</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Every 10 minutes, a new block of bitcoin transactions gets confirmed and added to the blockchain."),
                                Component.Text(text = "The creation of each block requires the identification of a specific number resulting from a complex mathematical puzzle."),
                                Component.Text(text = "The first miner to guess the correct number, receives <b>3.125 bitcoin</b> plus all transaction fees paid in the block."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "As a miner, you need hardware (called ASICs) specifically designed to mine bitcoin."),
                                Component.Text(text = "The more computing power you control, the more numbers per second you can guess, the more likely you are to be the first to guess correctly."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Each block is linked to the previous one, forming a chain that would be extremely costly to change."),
                                Component.Text(text = "Hacking the system means you'd need to forever win each block."),
                                Component.Text(text = "The high reward, extreme complexity, and randomness make the network’s security very strong."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Every four years, the reward per block is halved - in an event called the <b>halving</b>."),
                                Component.Text(text = "The last satoshi will be mined in 2140, upon which all 21,000,000 bitcoin will be in existence."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "How can you start mining bitcoin?"),
                                Component.Text(text = "A popular option for newcomers is <b>hosted mining</b>. A hosting service manages the hardware for you, charging a fee in return."),
                                Component.Text(text = "Joining a <b>mining pool</b> is another common strategy. Here, multiple miners combine their computational power, and share the rewards proportionally."),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Level(
            order = 2,
            lessons = listOf(
                Lesson(
                    id = "whatisbitcoincore",
                    title = "What is Bitcoin Core?",
                    image = "whatiscore",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "The bitcoin network runs on <b>software</b>. The original and most widely used software is called <b>Bitcoin Core</b>."),
                                Component.Text(text = "This software enables functions like <b>mining</b>, <b>validating transactions</b>, and <b>running nodes</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "A <b>bitcoin node</b> is any computer that's running software like Bitcoin Core."),
                                Component.Text(text = "Anyone can run a node. Tens of thousands of people do."),
                                Component.Text(text = "Nodes download the blockchain and independently verify all transactions. They keep the bitcoin network <b>decentralized</b>, secure, and functional."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin Core is <b>open-source</b>, meaning everyone can see its code."),
                                Component.Text(text = "Everyone can see exactly how bitcoin works. Everyone can view the entire blockchain and all transactions."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Anyone can collaborate on Bitcoin Core development, subject to an open review process."),
                                Component.Text(text = "New ideas are called <b>Bitcoin Improvement Proposals (BIP)</b>, which are discussed and tested rigorously."),
                                Component.Text(text = "Improvements are launched only upon wide community consensus. Nodes decide individually whether or not to adopt changes."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whatisaseedphrase",
                    title = "What is a seedphrase?",
                    image = "seedphrase",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "A <b>seed or recovery phrase</b> is a sequence of <b>12 or 24 words</b> used to recover your bitcoin wallet."),
                                Component.Text(text = "You can use it to regain access to your bitcoin if your wallet is lost, damaged, or otherwise compromised."),
                                Component.Text(text = "It should be stored <b>offline</b> and <b>never be shared</b> with anyone."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/1fbd2c8de1aa814992bedf45012b0a72.png"),
                                Component.Text(text = "You receive the seed phrase when creating a <b>self-custodial</b> wallet."),
                                Component.Text(text = "Since there's no third party, losing your seed phrase means losing access to your bitcoin permanently."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The most common type of seed phrase is <b>BIP 39</b>, which is made up from a predefined list of <b>2048 English words</b>."),
                                Component.Text(text = "This provides compatibility across most wallets."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/1fbd2c8de1aa81dea5cfc3c4ea6f03df.webp"),
                                Component.Text(text = "Keep your seed phrase <b>offline</b> in a physical format, like on paper. Never store it online."),
                                Component.Text(text = "You could create multiple copies and store them in secure locations, like safes."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "While seed phrases are a powerful self-custody tool, mishandling them can lead to loss."),
                                Component.Text(text = "Transfer your bitcoin to a new wallet if you suspect your seed phrase is compromised."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whoownsthemostbitcoin",
                    title = "Who owns the most bitcoin?",
                    image = "whoownsthemostbitcoin",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Almost <b>20 million</b> bitcoin (95 % of the total supply) have already been mined."),
                                Component.Text(text = "Though bitcoin is not a company and has no owner, it’s fairly possible to estimate who holds how much."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Around 66 % of bitcoin is held by <b>individuals</b>."),
                                Component.Text(text = "The largest one is <b>Coinbase</b>, which holds almost 3 million bitcoin (15 %) on behalf of its customers."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "With around 968,452 bitcoin (4.6 %), <b>Satoshi Nakamoto</b> is considered the largest individual holder."),
                                Component.Text(text = "These coins have remained untouched since 2010, and are considered permanently inactive."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Investment funds count for around 7.8 % of total bitcoin, the largest holder being <b>BlackRock iShares Bitcoin Trust</b>."),
                                Component.Text(text = "Companies hold around 6.2 % of the supply. Tesla, for example, holds around 11,500 bitcoin (0.06 %)."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Governments are estimated to hold a total of 1.5 % of all bitcoin."),
                                Component.Text(text = "The <b>U.S. government</b> holds around 213,000 bitcoin, mostly seized."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Large holdings do not confer power over the protocol. Rules are enforced by bitcoin nodes."),
                                Component.Text(text = "Ownership is purely private: whoever controls the private key controls the coins."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "sendingandreceivingbitcoin",
                    title = "Sending and receiving bitcoin",
                    image = "sendingandreceiving",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "To send and receive bitcoin, you need a <b>wallet</b>."),
                                Component.Text(text = "With a <b>self-custodial</b> wallet (like this app), you hold your own bitcoin and private keys."),
                                Component.Text(text = "With a <b>custodial</b> wallet, a middleman (like Coinbase) holds your bitcoin on your behalf."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "To receive bitcoin, your wallet generates <b>addresses</b>. Each wallet can generate unlimited addresses."),
                                Component.Text(text = "You can reuse addresses, or (for <b>privacy</b>) create a new address for each transaction."),
                                Component.Text(text = "All addresses and all bitcoin in them are public. What wallet an address belongs to isn't."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "To send bitcoin, you enter the <b>recipient's address</b>, the <b>amount</b>, and the <b>transaction fee</b>."),
                                Component.Text(text = "The higher the selected fee, the quicker a miner will include your transaction in their <b>block</b>."),
                                Component.Text(text = "Wallets usually recommend fees based on your urgency to get your transaction confirmed."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The amount barely impacts the fee, regardless of whether you send 100 bitcoin or 0.001 bitcoin."),
                                Component.Text(text = "The fee height fluctuates with demand, since blocks hold limited transactions and miners wish to maximize their returns."),
                                Component.Text(text = "If your fee is too low, your transaction may take days to - or never - get mined."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin transactions are <b>irreversible</b>, so make sure you enter the correct address and amount."),
                                Component.Text(text = "You can use a <b>block explorer</b> (like mempool.space) to check transaction statuses."),
                                Component.Text(text = "Once your transaction is mined into a block, that's one confirmation. Each following block is an additional confirmation. Typically, six confirmations is considered final."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whatislightning",
                    title = "What is lightning?",
                    image = "whatislightning",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin transactions can be <b>on-chain</b> or <b>off-chain</b>."),
                                Component.Text(text = "On-chain transactions are the ones that get <b>mined</b> onto a <b>block</b> on the blockchain."),
                                Component.Text(text = "These come with some limitations."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The blockchain is arguably the most <b>secure</b> financial database in existence."),
                                Component.Text(text = "But <b>fees</b> can get high and <b>confirmation times</b> can be slow."),
                                Component.Text(text = "Off-chain transactions (payments that <b>don't touch the blockchain</b>) address these issues."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The <b>lightning network</b> is such a solution."),
                                Component.Text(text = "With one on-chain transaction, <b>two users</b> lock up bitcoin in a <b>multisignature address</b>."),
                                Component.Text(text = "Inside this <b>payment channel</b>, they can send bitcoin back and forth, <b>instantly</b> and <b>without fees</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Either user can <b>close the channel</b>, settling their balance on the blockchain."),
                                Component.Text(text = "Or, through 3rd parties, users can <b>swap funds</b> between lightning and on-chain."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The lightning network is a <b>web</b> of <b>nodes</b> connected through <b>channels</b>."),
                                Component.Text(text = "If you have a channel with <b>Bob</b>, who has a channel with <b>Alice</b>, you can send instant payments to Alice without having a direct channel with her."),
                                Component.Text(text = "Such payments may incur <b>minor fees</b>, allowing you to instantly pay anyone (if a route can be found)."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Lightning payments are great for <b>frequent, small, private</b> transactions."),
                                Component.Text(text = "They're <b>faster</b> and <b>cheaper</b>, allowing bitcoin to <b>scale</b>."),
                                Component.Text(text = "Downsides are the need for <b>upfront funding</b>, and the <b>technical expertise</b> required."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "To stimulate bitcoin adoption, wallets like this one try to offer seamless switching between <b>regular transactions</b> and <b>instant payments</b>."),
                                Component.Text(text = "With bitcoin purchases under 100 €/CHF, bittr opens a channel with you."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "introductiontobitcoinwallets",
                    title = "Choosing a bitcoin wallet",
                    image = "introductiontowallets",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Your bitcoin exists only on the <b>blockchain</b>."),
                                Component.Text(text = "You have your <b>public keys</b> (addresses) to receive bitcoin, and your <b>private keys</b> (seedphrase) to send bitcoin."),
                                Component.Text(text = "A <b>bitcoin wallet</b> is a piece of <b>hardware or software</b> to store these keys, to manage your bitcoin."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "There are various types of wallets, with various levels of <b>security</b>."),
                                Component.Text(text = "With a <b>custodial wallet</b>, a 3rd party (like an exchange) holds your keys on your behalf."),
                                Component.Text(text = "While easy to use, this goes against bitcoin's ethos of \"<b>Not your keys, not your coins</b>\"."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "With a <b>self-custodial or non-custodial wallet</b>, you hold your own keys. These come as software or hardware."),
                                Component.Text(text = "A <b>software</b> wallet is an app (like this one) that's connected to the internet."),
                                Component.Text(text = "A <b>hardware</b> wallet is an offline device."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Software wallets are convenient to keep some bitcoin at hand for you to easily make transactions."),
                                Component.Text(text = "But any software that's connected to the internet, is always somewhat at risk to online threats."),
                                Component.Text(text = "If you hold significant bitcoin, a hardware wallet offers superior security."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "A hardware wallet can be paired with a <b>watch-only</b> software wallet."),
                                Component.Text(text = "This wallet only holds your public keys, so you can view your balance."),
                                Component.Text(text = "You can prepare transactions, which you sign with your hardware wallet."),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Level(
            order = 3,
            lessons = listOf(
                Lesson(
                    id = "whatisablockchain",
                    title = "What is a blockchain?",
                    image = "whatisablockchain",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "A blockchain is a <b>database</b> that stores data in <b>chronologically linked blocks</b>."),
                                Component.Text(text = "Data can be added, but it can never be altered or removed."),
                                Component.Text(text = "It offers a <b>single, verifiable version of history</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Blockchain was invented for bitcoin."),
                                Component.Text(text = "It solves the <b>double spend problem</b>: the ability to spend digital currency more than once."),
                                Component.Text(text = "This ensures that bitcoin (like physical currency) can only be spent once, moving from one address to another."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin is <b>trustless</b>."),
                                Component.Text(text = "You don't need to trust any single entity (like a bank or government) that your money is safe."),
                                Component.Text(text = "Accordingly, the blockchain is <b>public</b>. Anyone can download and verify the entire blockchain."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The blockchain is <b>decentralized</b>."),
                                Component.Text(text = "Tens of thousands of people (<b>nodes</b>) worldwide independently maintain their own copy."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The blockchain is <b>immutable</b>. Here's how:"),
                                Component.Text(text = "In encryption, you can run data through a mathematical formula to get a <b>hash</b>."),
                                Component.Text(text = "This hash (a long string of letters and numbers) is a unique digital fingerprint for that data."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Each block in the blockchain starts with the hash of the previous block."),
                                Component.Text(text = "Miners fill each block with 4 MB of data, around <b>3000 transactions</b>."),
                                Component.Text(text = "They pick these from the <b>mempool</b>, which holds all unconfirmed transactions."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "That data plus the hash of the previous block <b>form a new hash</b>."),
                                Component.Text(text = "However, that hash needs to meet certain conditions: the <b>difficulty rule</b>."),
                                Component.Text(text = "The difficulty gets updated every two weeks, to ensure that a block gets mined <b>every 10 minutes</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "To meet those conditions, miners try adding trillions of numbers (<b>nonces</b>) to the block's data."),
                                Component.Text(text = "<b>Hash of the previous block</b> + <b>new transactions</b> + <b>unknown nonce</b> = <b>new hash</b> that meets the <b>difficulty rule</b>."),
                                Component.Text(text = "The first miner to guess a correct nonce, <b>mines the block</b> and gets 3.125 bitcoin plus all transaction fees."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Since each hash is unique, and each block contains the previous block's hash, these blocks are <b>immutable</b>."),
                                Component.Text(text = "If you change anything, the entire chain breaks. To change one block, you need to change all following blocks."),
                                Component.Text(text = "The high investments required to mine blocks make this virtually impossible."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "howprivateisbitcoin",
                    title = "How private is bitcoin?",
                    image = "howprivateisbitcoin",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "A common misconception is that bitcoin is anonymous."),
                                Component.Text(text = "And that it's, therefore, used mostly by criminals."),
                                Component.Text(text = "But how private is bitcoin really?"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The blockchain is public."),
                                Component.Text(text = "Everyone can see every transaction, and the amount of bitcoin in every address."),
                                Component.Text(text = "These addresses, however, contain no personal information of the owner."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "This means that bitcoin is <b>pseudonymous</b>, not anonymous."),
                                Component.Text(text = "This pseudonymity provides privacy, while allowing anyone to audit the bitcoin supply."),
                                Component.Text(text = "If bitcoin were anonymous, there would be no way to verify the correct minting and movement of coins."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "However, bitcoin exchanges are often required to verify customer identities, above certain purchase thresholds."),
                                Component.Text(text = "This is enforced through <b>Know Your Customer (KYC)</b> regulations."),
                                Component.Text(text = "If requested, they must share these data with authorities."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Additionally, <b>blockchain analysis</b> companies exist."),
                                Component.Text(text = "These companies, through various strategies, try to trace what address and bitcoin belongs to whom."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Reduced privacy can lead to compromised safety. For example, for activists, dissidents, or opponents to oppressive regimes."),
                                Component.Text(text = "As bitcoin evolves, developers explore ways to preserve its pseudonymity."),
                                Component.Text(text = "Off-chain solutions (like <b>lightning</b>) enhance privacy by allowing for private transactions."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "canbitcoinbehacked",
                    title = "Can bitcoin be hacked?",
                    image = "canbitcoinbehacked",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "For <b>trustlessness</b>, it's important that bitcoin is secure against attacks."),
                                Component.Text(text = "The blockchain has <b>never been hacked</b>. Its decentralized nature makes attacks extremely difficult, technically and economically."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "In hacking, there's the <b>user level</b> and <b>network level</b>."),
                                Component.Text(text = "On the user level, if you're careless with your seedphrase, you can lose your coins."),
                                Component.Text(text = "Or if you get a custodial wallet, that 3rd party can get hacked or steal your coins."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "On the network level, how technically robust is bitcoin?"),
                                Component.Text(text = "The blockchain is maintained by tens of thousands of independent nodes worldwide."),
                                Component.Text(text = "You can't hack just a single computer, you'd need to hack tens of thousands."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Hacking the blockchain by <b>mining blocks</b> would require more computing power than all miners combined."),
                                Component.Text(text = "The high rewards and extreme competition, complexity, and randomness, make this extremely expensive if not impossible."),
                                Component.Text(text = "Even if you do mine a block with fraudulent transactions, the nodes would just reject the block."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Paradoxically, if you'd successfully hack the blockchain in order to enrich yourself, the value of bitcoin would fall."),
                                Component.Text(text = "The value of bitcoin relies entirely on its security and scarcity."),
                                Component.Text(text = "If not technically, then also economically, it's impossible to hack bitcoin and make a profit."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "What if the <b>internet goes down</b>? This would impact bitcoin, like it would impact all modern services."),
                                Component.Text(text = "Data would stay <b>intact</b> with all nodes, while they wait for the connection to return."),
                                Component.Text(text = "As bitcoin evolves, <b>alternative paths</b> are explored to run the network, not relying on the traditional internet."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "What about hypothetical <b>quantum computers</b>, breaking cryptography and computing power?"),
                                Component.Text(text = "This would compromise all modern services. Comparatively, bitcoin is exponentially more difficult to hack."),
                                Component.Text(text = "If such a threat would arise, bitcoin can evolve to anticipate it - as it's continuously doing."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "In conclusion, bitcoin remains unhacked and its security unmatched."),
                                Component.Text(text = "Any real threat to your funds, comes from carelessness with your keys."),
                                Component.Text(text = "Choose the appropriate wallets, and protect access to your keys and devices, and your coins will be secure."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "bitcoinversuscrypto",
                    title = "Bitcoin versus crypto",
                    image = "bitcoinversuscrypto",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "The words bitcoin and <b>crypto</b> are often inappropriately interchanged."),
                                Component.Text(text = "Bitcoin is a currency. Crypto refers to bitcoin and all <b>altcoins</b> that have spawned since."),
                                Component.Text(text = "These are not the same."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin has shown itself to be a strong, long-term store of value."),
                                Component.Text(text = "Its annual growth averages 60%."),
                                Component.Text(text = "In contrast, according to 2023 data, 90% of crypto traders lose money."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin was the first working crypto asset."),
                                Component.Text(text = "It has by far the largest <b>market cap</b> and the densest ecosystem, with the most users and infrastructure."),
                                Component.Text(text = "This network effect cannot be copy-pasted."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "It's difficult for altcoins to achieve true decentralization."),
                                Component.Text(text = "In practice, they all have a central authority - a company or a small dev team."),
                                Component.Text(text = "Also, they lack bitcoin's proven resilience: no network outages since 2013; overcome bear markets, bans, and controversies."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin's value comes from its fixed supply, transparent protocol, and proven security."),
                                Component.Text(text = "As an investment strategy, it offers proven long-term value over crypto's high-risk, short-term gains."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "bitcoinwhitepaperday",
                    title = "Bitcoin Whitepaper Day",
                    image = "bitcoinwhitepaperday",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/299d2c8de1aa8027ad0dd1cd0726e0c1.png"),
                                Component.Text(text = "Bitcoin, as a concept, was introduced on <b>31 October 2008</b>."),
                                Component.Text(text = "On that day, the pseudonymous <b>Satoshi Nakamoto</b> published <b>Bitcoin: A Peer-to-Peer Electronic Cash System</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The timing of the release, weeks after the Lehman Brothers collapse, was likely no coincidence."),
                                Component.Text(text = "The modest 9-page document became the starting point of a financial shift."),
                                Component.Text(text = "It laid the foundation for bitcoin’s rise in the following years."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "That date, 31 October, is now known as <b>Bitcoin Whitepaper Day</b>."),
                                Component.Text(text = "It's meant to celebrate the start of this movement, and the birth of the first decentralized cryptocurrency system."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Nakamoto introduced bitcoin to address core weaknesses in traditional money."),
                                Component.Text(text = "It emphasized <b>trustlessness</b>: creating a <b>decentralized</b> peer-to-peer network with no central middlemen."),
                                Component.Text(text = "It explained the <b>blockchain</b>, as a way to solve the <b>double-spend problem</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "It announced the <b>fixed supply</b> of 21 million coins, to protect against inflation."),
                                Component.Text(text = "It aimed for <b>financial inclusion and global access</b>, offering an open financial system to the 1.4 billion people worldwide without bank accounts."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin represents <b>freedom in finance</b>, and challenges conventional ideas about money and ownership."),
                                Component.Text(text = "It stands for <b>financial sovereignty</b>: individuals hold full control over their assets and transactions."),
                                Component.Text(text = "It's a movement that puts financial self-determination at the center."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "bitcoinforbidden",
                    title = "What if bitcoin gets forbidden?",
                    image = "forbiddenbitcoin",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin challenges the status quo of fiat money."),
                                Component.Text(text = "For some governments, that’s a threat."),
                                Component.Text(text = "That raises the question: <b>could governments ban bitcoin entirely?</b>"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Why might governments want to ban bitcoin?"),
                                Component.Text(text = "Firstly, for bitcoin's <b>privacy</b>. Its pseudonymity allows individuals to transact outside of state surveillance."),
                                Component.Text(text = "Secondly, bitcoin is <b>censorship resistant</b>. Transactions cannot be reversed or blocked, unlike bank accounts which can be frozen."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Thirdly, because of <b>competition</b>. Some states' monetary authority relies on its control of its fiat currency."),
                                Component.Text(text = "If people switch to bitcoin, this reduces the power of that currency."),
                                Component.Text(text = "It could also allow individuals to sidestep sanctions."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "<b>China</b> has declared bitcoin illegal multiple times. But mining and trading have continued."),
                                Component.Text(text = "<b>India</b> has attempted a ban, which was struck down by its Supreme Court."),
                                Component.Text(text = "In 2021, <b>Nigeria</b> banned bank involvement in crypto, which conversely led to a dramatic spike in bitcoin adoption."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "How could governments shut down bitcoin?"),
                                Component.Text(text = "One way would be <b>banning regulated platforms</b>. This would make it harder for citizens to buy or sell bitcoin."),
                                Component.Text(text = "This wouldn't influence the bitcoin network itself, though it could hurt adoption."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Another way would be for governments to <b>attack the network</b>."),
                                Component.Text(text = "But hacking the bitcoin network is, technically and economically, virtually impossible. It's designed to be resilient to exactly this kind of censorship."),
                                Component.Text(text = "Even if a government blocked all domestic nodes, users could still connect through VPNs."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "What about a coordinated, global ban?"),
                                Component.Text(text = "Governments could ban exchanges, and block internet access to bitcoin-related services."),
                                Component.Text(text = "They could pressure social platforms to censor bitcoin content, and classify self-custody wallets as illegal."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "That kind of unified effort is unlikely."),
                                Component.Text(text = "Different countries have very different regulatory goals."),
                                Component.Text(text = "Plus, any nation choosing not to join the ban would benefit from capital inflow, innovation, and bitcoin businesses relocating."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Actually, in democratic countries, voters and lawmakers are increasingly bitcoin-friendly"),
                                Component.Text(text = "Bitcoin creates jobs, attracts investment, and generates tax revenue."),
                                Component.Text(text = "Some governments actively embrace bitcoin, to attract innovation."),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Level(
            order = 4,
            lessons = listOf(
                Lesson(
                    id = "badfortheenvironment",
                    title = "Is bitcoin bad for the environment?",
                    image = "badfortheenvironment",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Critics often claim that bitcoin is bad for the environment."),
                                Component.Text(text = "How does bitcoin consume energy, what kind, and how might this evolve?"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Miners compete to mine blocks, by being the first to guess a correct nonce."),
                                Component.Text(text = "The more computing power a miner controls, the quicker they can guess, the more likely they win."),
                                Component.Text(text = "More computing power requires more energy."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Mining is energy-heavy by design, to guarantee the decentralized and immutable blockchain."),
                                Component.Text(text = "The physical cost to mine blocks makes it extremely expensive to cheat the system."),
                                Component.Text(text = "Bitcoin uses physics to secure the network: <b>energy replaces trust</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Miners are incentivized to use the cheapest energy available, which is often renewable energy."),
                                Component.Text(text = "A 2020 Cambridge study found that <b>76%</b> of bitcoin mining comes from renewable energy."),
                                Component.Text(text = "Miners often set up in remote areas with abundant renewable energy."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Image(url = "https://bittr-notion-bucket.s3.eu-central-2.amazonaws.com/notion-media/1fbd2c8de1aa816380c3db62c929857c.jpg"),
                                Component.Text(text = "In 2022, bitcoin mining consumed 0.16% of global electricity."),
                                Component.Text(text = "That's significantly less than traditional banking and gold mining operations."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Off-chain innovations, like <b>lightning</b>, make bitcoin less energy-consuming as it scales."),
                                Component.Text(text = "In this way, bitcoin becomes more efficient, while safeguarding its trustlessness."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "bitcoinforks",
                    title = "What are bitcoin forks?",
                    image = "bitcoinforks",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin exists only on the blockchain."),
                                Component.Text(text = "Wallets, nodes, and miners use software (like <b>Bitcoin Core</b>) to interact with it."),
                                Component.Text(text = "This software is <b>open source</b>: everyone can see and modify its code."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "This software abides by the <b>bitcoin protocol</b>: the strict rules by which bitcoin operates."),
                                Component.Text(text = "Software updates can change the protocol."),
                                Component.Text(text = "Since this is <b>decentralized</b>, not all users immediately adopt changes. And some users may disagree with a change and never upgrade."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "This presents a challenge: how can a network maintain consensus while evolving?"),
                                Component.Text(text = "The answer lies in <b>forks</b>: updates that either maintain or break compatibility with the existing protocol."),
                                Component.Text(text = "We call these <b>soft forks</b> and <b>hard forks</b>."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Soft forks are <b>backward-compatible</b>."),
                                Component.Text(text = "This means that nodes running old software can still recognize and validate transactions under newer rules."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Hard forks <b>break compatibility</b>."),
                                Component.Text(text = "This splits the blockchain into <b>two independent chains</b>. The original one, and the one for users that accept the new changes."),
                                Component.Text(text = "This has never successfully been done."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Bitcoin’s community avoids hard forks whenever possible."),
                                Component.Text(text = "Hard forks create a new cryptocurrency, independent from bitcoin."),
                                Component.Text(text = "This risks fragmenting the network, weakening security, and confusing users."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "This mechanism ensures that only widely-accepted changes make it into the protocol."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "21millionlimit",
                    title = "Can the 21 million limit be changed?",
                    image = "21millioncoins",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "One of bitcoin's defining traits is its <b>predictable scarcity</b>."),
                                Component.Text(text = "Only <b>21 million bitcoin</b> will ever exist, 95% of which already do."),
                                Component.Text(text = "Miners receive new bitcoin (and transaction fees) when mining a block."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Upon bitcoin's inception, miners received 50 bitcoin per block."),
                                Component.Text(text = "Every four years, this reward is reduced by 50%, referred to as <b>the halving</b>."),
                                Component.Text(text = "Currently, miners receive 3.125 bitcoin per block."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The next halving will happen in April 2028."),
                                Component.Text(text = "The final satoshi will be mined in the year 2140, after which no new coins will enter circulation."),
                                Component.Text(text = "Miners will then only receive transaction fees for their work."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "This scarcity protects bitcoin against inflation."),
                                Component.Text(text = "And the halving creates upward price pressure, if demand for bitcoin holds steady or grows."),
                                Component.Text(text = "But could these rules be changed, e.g. if miners would want to?"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "These rules are lines of code in open-source softwares, and could be changed with an update."),
                                Component.Text(text = "The question is whether the tens of thousands of nodes that maintain and validate the blockchain, will accept such a change."),
                                Component.Text(text = "Such a change would be a <b>hard fork</b>. It would create a new currency that only those who agree will adopt."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "A change to this core principle is extremely unlikely."),
                                Component.Text(text = "It would erode confidence in bitcoin, likely leading to a hard fall in value."),
                                Component.Text(text = "Nobody would benefit economically from such an event."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "Miners don't make the rules, tens of thousands of nodes do."),
                                Component.Text(text = "Any attempt to inflate supply would split off a new coin, not change bitcoin."),
                            ),
                        ),
                    ),
                ),
                Lesson(
                    id = "whatisutxomanagement",
                    title = "What is UTXO management?",
                    image = "whatisutxomanagement",
                    pages = listOf(
                        Page(
                            components = listOf(
                                Component.Text(text = "Each block on the blockchain can hold <b>4 MB of data</b> (around 3000 transactions)."),
                                Component.Text(text = "Miners fill each block with transactions that maximize the fees they receive."),
                                Component.Text(text = "So the larger the transaction size in bytes, the higher the fee you need to pay. <b>But what determines the size?</b>"),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "When someone sends you bitcoin, you receive one <b>unspent transaction output (UTXO)</b>."),
                                Component.Text(text = "Example: Bob sends you 1 btc and Alice sends you 2 btc. Now you have 2 UTXOs, worth 1 btc and 2 btc."),
                                Component.Text(text = "Now you send 2.5 btc to John. You use your 2 UTXOs. John receives 1 UTXO worth 2.5 btc. As <b>change</b> you receive 1 UTXO worth 0.5 btc (minus the fee)."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "The more UTXOs make up your transaction, the larger its size."),
                                Component.Text(text = "So the fees you must pay, depend on the amount of UTXOs being spent, not on the transaction amount."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "With <b>UTXO management</b>, you can try to keep these fees low."),
                                Component.Text(text = "You can <b>consolidate</b> your UTXOs by sending a transaction to yourself. At a time when transaction fees are relatively low."),
                                Component.Text(text = "This takes all your small UTXOs and creates one large UTXO."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "You need to consider your privacy though."),
                                Component.Text(text = "Someone who has sent you bitcoin can see the UTXO that you've received."),
                                Component.Text(text = "If you link that UTXO with other UTXOs, they can deduce details about your past and future transactions."),
                            ),
                        ),
                        Page(
                            components = listOf(
                                Component.Text(text = "UTXOs acquired via bittr can be consolidated without worries. No third parties are involved."),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}
