#!/usr/bin/env python3
"""Transcribe the iOS Academy demo data into the Android content source.

`ios/bittr/Academy/Academy/AcademyVC/Demo Data.swift` is 2,161 lines of
hand-built object graph: four levels, twenty-two lessons, and every sentence the
Academy shows. Retyping it is how a lesson silently loses a page or gains a typo,
and nothing in either build would notice — the Maestro flow pages until Next is
gone, so a lesson with one page fewer still passes.

So it is transcribed mechanically, and this script is the transcription. It is
not part of the Gradle build: the output is committed, because the source is a
file in the *iOS* tree and a build that reaches across into it would break the
moment the two trees are split. Re-run it when the iOS demo data changes:

    python3 tools/academy_content.py

Structure recognised, which is exactly the shape the Swift uses:

    let x = Component() / x.type = .label|.image / x.text = "…" / x.url = "…"
    let p = Page()      / p.components = [a, b]
    let l = Lesson()    / l.pages = […] / l.title / l.id / l.image
    let v = Level()     / v.lessons = […]
    return [level1, …]

Assignments are gathered by name first and resolved afterwards, because the Swift
does not keep a consistent order — `lesson2.pages` comes before its title, `l4l4`'s
after.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "ios/bittr/Academy/Academy/AcademyVC/Demo Data.swift"
TARGET = (
    REPO
    / "android/feature/academy/src/main/kotlin/com/bittr/android/feature/academy/AcademyContent.kt"
)

DECL = re.compile(r"^\s*let (\w+) = (Component|Page|Lesson|Level)\(\)\s*$")
ASSIGN = re.compile(r"^\s*(\w+)\.(\w+) = (.+?)\s*$")
LIST = re.compile(r"^\[(.*)\]$")
RETURN = re.compile(r"^\s*return \[(.+)\]\s*$")


def parse(text: str):
    kinds: dict[str, str] = {}
    fields: dict[str, dict[str, str]] = {}
    levels: list[str] = []

    for line in text.splitlines():
        declaration = DECL.match(line)
        if declaration:
            name, kind = declaration.groups()
            kinds[name] = kind
            fields.setdefault(name, {})
            continue

        returned = RETURN.match(line)
        if returned:
            levels = [item.strip() for item in returned.group(1).split(",")]
            continue

        assignment = ASSIGN.match(line)
        if assignment:
            name, field, value = assignment.groups()
            if name in kinds:
                fields[name][field] = value

    return kinds, fields, levels


def swift_string(value: str) -> str:
    """A Swift string literal → its Kotlin equivalent.

    The two languages agree on `\\"` and `\\\\`, which is every escape the source
    uses; anything else is refused rather than passed through, because a silently
    mistranslated escape is exactly the failure this script exists to avoid. The
    one real difference is `$`, which Kotlin reads as a template opener.
    """
    if not (value.startswith('"') and value.endswith('"')):
        raise ValueError(f"not a string literal: {value}")
    inner = value[1:-1]
    for escape in re.finditer(r"\\(.)", inner):
        if escape.group(1) not in '"\\':
            raise ValueError(f"unexpected escape, check by hand: {value}")
    return '"' + inner.replace("$", "\\$") + '"'


def items(value: str) -> list[str]:
    match = LIST.match(value)
    if not match:
        raise ValueError(f"not a list literal: {value}")
    return [item.strip() for item in match.group(1).split(",") if item.strip()]


def emit(kinds, fields, levels) -> str:
    out: list[str] = []
    w = out.append

    w("// AUTO-GENERATED by tools/academy_content.py. DO NOT EDIT.")
    w("// Source: ios/bittr/Academy/Academy/AcademyVC/Demo Data.swift")
    w("")
    w("package com.bittr.android.feature.academy")
    w("")
    w("/**")
    w(" * The Academy's lessons, transcribed from the iOS demo data.")
    w(" *")
    w(" * iOS builds this graph in `getDemoData()` and caches it on the Core view")
    w(" * controller under `downloadedAcademy`, behind a branch that would download it")
    w(" * instead if a backend existed (`AcademyViewController.swift:43-53`). It does not")
    w(" * yet, on either platform, so both ship the same constant — and it has to *be* the")
    w(" * same constant: lesson ids are the completion keys, so a divergence here would")
    w(" * mean a lesson completed on iOS reading as locked on Android for the same user.")
    w(" */")
    w("internal object AcademyContent {")
    w("")
    w("    val levels: List<Level> = listOf(")

    for order, level in enumerate(levels, start=1):
        lessons = items(fields[level]["lessons"])
        w(f"        Level(")
        w(f"            order = {order},")
        w(f"            lessons = listOf(")
        for lesson in lessons:
            lesson_fields = fields[lesson]
            w("                Lesson(")
            w(f"                    id = {swift_string(lesson_fields['id'])},")
            w(f"                    title = {swift_string(lesson_fields['title'])},")
            image = lesson_fields.get("image")
            w(f"                    image = {swift_string(image) if image else 'null'},")
            w("                    pages = listOf(")
            for page in items(lesson_fields["pages"]):
                w("                        Page(")
                w("                            components = listOf(")
                for component in items(fields[page]["components"]):
                    component_fields = fields[component]
                    kind = component_fields.get("type", ".label")
                    if kind == ".image":
                        url = swift_string(component_fields["url"])
                        w(f"                                Component.Image(url = {url}),")
                    else:
                        text = swift_string(component_fields["text"])
                        w(f"                                Component.Text(text = {text}),")
                w("                            ),")
                w("                        ),")
            w("                    ),")
            w("                ),")
        w("            ),")
        w("        ),")

    w("    )")
    w("}")
    w("")
    return "\n".join(out)


def main() -> int:
    kinds, fields, levels = parse(SOURCE.read_text(encoding="utf-8"))
    if not levels:
        print("no `return [level…]` found — the Swift shape has changed", file=sys.stderr)
        return 1

    kotlin = emit(kinds, fields, levels)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(kotlin, encoding="utf-8")

    lessons = sum(len(items(fields[level]["lessons"])) for level in levels)
    print(f"{TARGET.relative_to(REPO)}: {len(levels)} levels, {lessons} lessons")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
