//
//  Language.swift
//  bittr
//
//  Created by Tom Melters on 07/10/2024.
//

import UIKit

class Language: NSObject {
    
    static func getWord(withID:String) -> String {
        
        if CacheManager.getLanguage() == "en_US" {
            return fromEnUS(withID: withID)
        } else {
            return ""
        }
    }
    
    static func fromEnUS(withID:String) -> String {
        
        let allWords:[String:String] = [
            "yourwallet": "your wallet",
            "syncing": "Syncing",
            "send": "Send",
            "receive": "Receive",
            "buy": "Buy",
            "totalprofit": "Total profit",
            "notransactions1": "There are no transactions. Tap ",
            "notransactions2": " to get your first bitcoin.",
            "transaction": "transaction",
            "instant": "Instant",
            "regular": "Regular",
            "amount": "Amount",
            "type": "Type",
            "id": "ID",
            "description": "Description",
            "currentvalue": "Current value",
            "purchasevalue": "Purchase value",
            "profit": "Profit",
            "addanote": "Add a note",
            "feespaid": "Fees paid",
            "confirmations": "Confirmations",
            "sats": "sats",
            "news": "news",
            "questions": "questions",
            "noarticles": "There are no articles.",
            "getsupport": "Get support",
            "restorewallet": "Restore wallet",
            "wipewallet": "Wipe wallet",
            "privacypolicy": "Privacy Policy",
            "termsandconditions": "Terms & Conditions",
            "currency": "Currency",
            "walletandbalance": "Wallet and balance",
            "devicedetails": "Device details",
            "devicedetails2": "device details",
            "appversion": "App version",
            "enteryourpincode": "Enter your PIN",
            "confirm": "Confirm",
            "setapin": "Set a PIN for secure access to your wallet",
            "confirmyourpin": "Confirm your PIN",
            "back": "Back",
            "next": "Next",
            "balance": "balance",
            "balance2": "Balance",
            "walletsubtitle": "These are the funds in your bittr wallet and lightning connection.",
            "lightningchannels": "lightning connections",
            "lightningexplanation1": "To send and receive instant bitcoin payments, you need to have at least one lightning connection.\n\nTo open a connection with bittr, buy bitcoin worth up to 100 CHF/EUR to receive a lightning connection. Check your wallet's Buy section or getbittr.com for all information.",
            "lightningchannel": "lightning connections",
            "sendbitcoin": "send bitcoin",
            "sendtoplabel": "Send bitcoin from your bitcoin wallet to another bitcoin wallet. Scan a QR code or input manually.",
            "sendtoplabellightning": "Send bitcoin from your bitcoin lightning wallet to another bitcoin lightning wallet.",
            "address": "Address",
            "invoice": "Invoice",
            "sendall": "Send all <amount> BTC",
            "youcansend": "You can send <amount> satoshis.",
            "enterinvoice": "Enter invoice",
            "enteraddress": "Enter address",
            "enteramount": "Enter amount",
            "confirmtransaction": "confirm transaction",
            "checkdetails": "Make sure these details are correct.",
            "feerate": "Select your preferred fee rate.",
            "edit": "Edit",
            "limitlightning": "why a limit for instant payments?",
            "limitlightninganswer": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning connection (for instant payments).\n\nIf you've received satoshis into your lightning connection, you can use those to pay lightning invoices.\n\nYou cannot make instant payments that exceed the funds in your lightning connection.",
            "checkyourconnection": "Check your connection",
            "trytoconnect": "You don't seem to be connected to the internet. Please try to connect.",
            "okay": "Okay",
            "receivebitcoin": "receive bitcoin",
            "thisisanaddress": "This is an address to your bitcoin wallet.",
            "createaninvoice": "Create a Lightning invoice to receive bitcoin instantly to your Lightning wallet.",
            "amountinsatoshis": "Amount",
            "youcanreceive": "You can receive up to",
            "enterdescription": "Enter description",
            "createinvoice": "Invoice",
            "lightninginvoice": "lightning invoice",
            "thisisyourinvoice": "This is your Lightning invoice.",
            "done": "Done",
            "copied": "Copied",
            "theresalimit": "There's a limit to the amount of satoshis you can receive per invoice.\n\nYour lightning connection has a size, ten times the amount of your first bittr purchase. If the size is 10,000 sats and you've already received 2,000 sats, you can still receive up to 8,000 sats in total.\n\nWhen the connection is full, we'll invite you to move your funds to your regular bitcoin wallet to make space for future transactions.",
            "oops": "Oops!",
            "addressfail": "We couldn't fetch a wallet address. Please try again.",
            "tryagain": "Try again",
            "addressfail2": "We couldn't fetch a wallet address",
            "pleasetryagain": "Please try again",
            "cancel": "Cancel",
            "unexpectederror": "Unexpected error",
            "error": "Error",
            "scanningnotsupported": "Scanning not supported",
            "scanningnotavailable": "Your device does not support scanning a code from an item. Please use a device with a camera.",
            "noaddressfound": "No address found.",
            "pleasescan": "Please scan a bitcoin or lightning address QR code or input the address manually.",
            "nobitcoinaddressfound": "No bitcoin address found.",
            "pleasescan2": "Please scan a bitcoin address QR code or input the address manually.",
            "spendablebalance": "Make sure the amount of BTC you wish to send is within your spendable balance.",
            "cannotproceed": "We couldn't proceed to the next step",
            "highfeerate": "High fee rate",
            "highfeerate2": "The fee you've selected costs more than 10 % of the bitcoin you're sending. Make sure this is as intended.",
            "insufficientonchainbalance": "Your available balance (<fee>) is insufficient to cover this fee.",
            "updateamount": "Update amount",
            "close": "Close",
            "lowfee": "Low fee",
            "lowfee2": "The fee you've selected is very low. Your transaction may take long to (or never) be confirmed.",
            "changefee": "Change fee",
            "continue": "Continue",
            "sendtransaction": "Send transaction",
            "sendconfirmation": "Are you sure you want to send <b><amount> satoshis</b>, with a fee of <b><fees> satoshis</b>, to <b><address></b>?",
            "success": "Success",
            "success2": "success",
            "transactionsuccess": "Your transaction has been sent and will show up in your wallet shortly.",
            "transactionerror": "We're unable to complete your transaction. We're receiving the following error message",
            "transactionerror2": "We're unable to complete your transaction. Please close and reopen our app and try again.",
            "paymentsuccessful": "Payment successful",
            "paymentfailed": "Payment failed",
            "paymentfailed2": "Your Lightning payment didn't go through.<reason>\n\nLightning payments can fail when the receiver is offline or doesn't have the app open, when their wallet doesn't have enough receiving capacity, when there's no affordable route through the network, or when the invoice has expired. Try again later or ask the receiver to open their app.",
            "paymentfailed3": "Unable to send bitcoin payment. Please sync your wallet and try again.",
            "buybitcoin": "buy bitcoin",
            "buysubtitle": "To buy bitcoin, make a bank transfer to a partner and put your unique code in the transfer description field.",
            "buyempty": "No order has been set up. Tap below to create your first one.",
            "addanother": "add another",
            "youremail": "Your email",
            "youriban": "Your IBAN",
            "ouriban": "Partner IBAN",
            "ourname": "Partner",
            "yourcode": "Your code",
            "yourprofits": "your profits",
            "profitsubtitle": "Here's to financial independence! These are the results of your savings so far.",
            "totalinvestment": "Total investment",
            "finaldetails": "Finish",
            "letsgo": "Let's go",
            "readyfortransfer": "We're ready for your transfer!",
            "personaldetails": "These are your personal details. To buy bitcoin, make a bank transfer at any time and include your unique code in the transfer description/memo field.",
            "screenshot": "Screenshot",
            "youvegotmail": "You've got mail! Please enter your verification code below.",
            "entercode": "Enter code",
            "resendcode": "Resend code",
            "bittrinstructions4": "Buy bitcoin whenever you want, simply by making a bank transfer.",
            "whatsyouriban": "What's your IBAN (International Bank Account Number)?",
            "whatsyouremail": "What's your email address?",
            "enteriban": "Enter IBAN",
            "enteremail": "Enter email",
            "verify": "Verify",
            "noiban": "I don't have an IBAN",
            "walletisready": "Your wallet is ready!",
            "firstbitcoin": "Get your first bitcoin, hassle-free, here with one of our partners.",
            "skip": "Skip",
            "incorrectpin": "Incorrect PIN",
            "repeatnumber": "Repeat the same number.",
            "confirmrecoveryphrase": "Enter these words to confirm your recovery phrase.",
            "enterword": "Enter word",
            "recoveryphrase": "This is your 12-word recovery phrase. It's crucial that you store it safely where no one can access it.",
            "recoveryphrase2": "This is your only opportunity to see it and save it.",
            "checkandconfirm": "Check and confirm that you understand the following details.",
            "checkandconfirm1": "With bitcoin, you are your own bank. No one else has access to your private keys.",
            "checkandconfirm2": "If you lose access to this app and your backup, your bitcoin cannot be recovered.",
            "iunderstand": "I understand",
            "welcome": "welcome",
            "createyourownwallet": "Create your own bittr wallet and buy bitcoin directly from your banking app.",
            "createwallet": "Create wallet",
            "becareful": "Be careful!",
            "noscreenshot": "We'd highly recommend against screenshotting your recovery phrase.\n\nScreenshots can easily be accessed by others, who will have full access to your wallet.",
            "enterrecoveryphrase": "Enter your 12-word recovery phrase.",
            "accessdetails": "Access your device details in case you need our support.",
            "darkmode": "Dark mode",
            "devicetoken": "Device token",
            "fetch": "Fetch",
            "publickey": "Public key",
            "bittrpeer": "Bittr peer",
            "check": "Check",
            "bittrpurchases": "Bittr purchases",
            "bittrnotification": "Bittr notification",
            "retry": "Retry",
            "lightningchannels2": "Lightning connections",
            "cachedimages": "Cached images",
            "empty": "Empty",
            "goodjob": "Good job, you've just added new satoshis to your bitcoin piggy bank!",
            "newpayment": "You've received a new payment!",
            "fundingtx": "Channel funding transaction",
            "questionvc1": "There's a limit to the amount of satoshis you can receive per invoice.\n\nThe size of your bitcoin lightning connection is <b><channelsize> satoshis</b>. You've already received <b><channelbalance> sats</b>, so you can still receive up to <b><receivelimit> sats</b> in total.\n\nWhen the connection is full, we'll invite you to move your funds to your regular bitcoin wallet to make space for future transactions.",
            "questionvc6": "why can't I send instant payments?",
            "questionvc7": "As part of your bittr wallet, you have a <b>bitcoin wallet</b> (for regular payments) and a <b>bitcoin lightning connection</b> (for instant payments).\n\nYour lightning balance is <b><channelbalance> satoshis</b>. The connection needs to contain a minimum of <b><channelreserve> sats</b>, so you can send up to <b><sendlimit> sats</b>.",
            "questionvc12": "why can't I receive instant payments?",
            "questionvc13": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning connection (for instant payments).\n\nYou don't currently have a lightning connection.\n\nTo open a connection with bittr, buy bitcoin worth between 20 and 100 €. Check your wallet's Buy section or getbittr.com for all information.",
            "reserve": "reserve",
            "total": "total",
            "walletconnectfail": "Something went wrong starting your wallet. Please try again. If the issue persists, contact support@getbittr.com",
            "walletconnectfail2": "We couldn't load your new transactions. Please close and reopen this app to try again.",
            "bittrpayout": "Bittr payout",
            "incomingpayment": "Incoming payment",
            "htlc_expired_title": "Payment expired",
            "htlc_expired_body": "When someone tries to pay you via Lightning, we send you a notification. You have about 5 minutes to open the app so the payment can go through.\n\nWith Lightning, both you and the sender need to have the app open. Regular bitcoin payments are different: you can receive those even when you're offline.",
            "newbittrpayment": "You're receiving a new payment! Tap Okay to receive it now and continue what you're doing after.",
            "receivingpayment": "receiving payment",
            "pleasesignin": "Please sign in and wait a moment to receive your payment.",
            "pleasesignintosend": "Please sign in to send this payment.",
            "couldntconnect": "We couldn't connect to bittr. Please try again.",
            "bittrpayoutfail": "The notification did not contain the data needed to complete your payout.",
            "bittrpayoutfail2": "Something went wrong processing the notification we sent to you.\n\nPlease wait for your wallet to sync, and try again. Or go to Settings > Device details, and try again from there.",
            "htlcnoheld": "There's no incoming Lightning payment waiting for you anymore. Lightning payments need the app open within a few minutes to go through, so this one likely expired — please ask the sender to try again.",
            "closedlightningchannel": "closed lightning connection",
            "closedlightningchannel2": "Your lightning connection has been closed.<reason>\n\nAny funds that were in this connection are deposited into your bitcoin wallet.\n\nTo open a new connection with bittr, buy bitcoin worth up to 100 CHF/EUR. Check your wallet's Buy section or getbittr.com for all information.",
            "closedlightningchannel3": " We've been notified that ",
            "bittrnotificationfail": "Something went wrong processing the notification we sent to you. Please contact support@getbittr.com if you have any questions.",
            "pinlock": "You've entered an incorrect PIN too many times. Please restore your wallet.",
            "tokenregistrationfail": "We couldn't register this device for notifications. Please check your internet connection and try again, or continue with regular payouts.",
            "keychainunavailabletitle": "Couldn't access your wallet",
            "keychainunavailable": "We couldn't securely read your wallet just now. This can happen right after unlocking your device or when the phone is busy — your wallet and funds are safe.\n\nPlease tap Try again. Do not delete the app from your phone.",
            "mnemonicsavefail": "Something went wrong securely saving your wallet. Please try again.",
            "incorrectpin2": "Please enter your correct PIN. If you've forgotten it, please restore your wallet.",
            "pinattemptsleft": "You have <attempts> attempts left.",
            "pinattemptleft": "You have 1 attempt left.",
            "restorewallet2": "Are you sure you'd like to remove this wallet from your device?\n\nOnly remove your wallet if you're sure you've properly backed up your wallet.",
            "restore": "Restore",
            "restorewallet3": "Are you sure you want to remove your wallet from this device?",
            "restorewallet4": "Please close your lightning connection(s) before removing your wallet from this device.\n\nOtherwise, you may lose access to the funds in your lightning connection.",
            "closechannel": "Close connection(s)",
            "closechannel2": "If you close your lightning connection(s), its funds will be deposited back into your wallet.\n\nPlease wait for this transaction to show up, before definitively removing this wallet from your device.",
            "closechannel3": "Your lightning connection has been closed. Wait for any remaining funds to reappear in your wallet before removing this wallet from your device.",
            "closechannel4": "We could not close your lightning connection. Please try again.",
            "closechannel6": "Connection Closure Issue",
            "closechannel7": "The lightning connection could not be closed normally, possibly because the bittr node is offline or there's a connection issue.\n\nYou can close the connection unilaterally (force close), but this will require higher transaction fees and may take longer to complete.",
            "forceclose": "Force Close",
            "forceclose2": "Force closing the connection will require higher transaction fees but will work even if the bittr node is offline.",
            "forceclose3": "Force close also failed. Please try again later or contact support.",
            "forceclose4": "Force close initiated successfully. This may take longer than normal closure due to higher transaction fees.",
            "pinwarning": "Warning",
            "pinwarning2": "You've entered the wrong PIN several times. After 10 failed attempts this wallet will be erased from the device, and any Bitcoin or Lightning funds it holds may be permanently lost.\n\nIf you still have your 12-word recovery phrase, tap \"Forgot PIN\" to reset your PIN instead — this keeps your wallet and your funds.\n\nNever delete the app from your phone, as this can also lead to loss of funds.",
            "stillclosing": "Your Lightning connection is still being closed. For your safety, the wallet can only be reset once the connection is fully closed and the funds have returned on-chain — this can take a while.\n\nPlease reopen the app later to finish the reset. Do not delete the app from your phone, as this will lead to loss of funds.",
            "closeretrylater": "Your Lightning connection could not be closed right now — the bittr node may be temporarily offline. Your wallet has not been reset.\n\nPlease reopen the app to try again later. Do not delete the app from your phone, as this will lead to loss of funds.",
            "removalfailed": "Something went wrong removing your wallet, so it hasn't been removed — your wallet and funds are safe.\n\nPlease reopen the app to try again. Do not delete the app from your phone.",
            "restoredbackup": "Wallet restored",
            "restoredbackup2": "It seems that this wallet was restored from a backup. Your Lightning connection could not be carried over.\n\nIf you need our help, please contact support@getbittr.com.",
            "pinlength": "PIN Length",
            "pincanbeupto8": "PIN can be up to 8 digits",
            "pinrequired": "PIN Required",
            "pinshouldbe4to8": "PIN should be between 4 and 8 digits",
            "syncingwallet": "Syncing wallet",
            "syncingwallet3": "syncing wallet",
            "syncingwallet2": "Please wait a moment while we're syncing your wallet.",
            "resendcode2": "Please wait 30 seconds before requesting another verification code.",
            "changeemail": "Change email",
            "conversionfail": "We're experiencing an issue fetching the latest conversion rates. Temporarily, our calculations - if available - won't reflect bitcoin's current value.",
            "unconfirmed": "Unconfirmed",
            "save": "Save",
            "lightningchannelfees": "lightning connection fees",
            "lightningchannelfees2": "This is your first instant bitcoin transaction.\n\nTo enable instant payments, we need to reserve funds in a lightning connection for you.\n\nThis fee covers both the capital we reserve (so you can make instant transactions) and the bitcoin network fees for opening and closing the connection.\n\nAll future instant bitcoin purchases will be completely free of network fees.",
            "copy": "Copy",
            "cachedimages1": "Are you sure you want to remove your cached images?",
            "remove": "Remove",
            "cacheemptied": "Cache emptied",
            "cachedimages2": "Any cached images have been removed.",
            "bittrpeer2": "You're connected to bittr.",
            "bittrpeer3": "You're not connected to bittr.",
            "connect": "Connect",
            "bittrtransactions": "Bittr transactions",
            "bittrtransactions2": "Would you like to fetch additional information about your bittr purchases?",
            "bittrtransactions3": "New information has been received. Your transactions have been refreshed.",
            "bittrtransactions4": "No new information is available.",
            "bittrnotification2": "There is no notification available for handling.",
            "bankingapp": "Open your banking app",
            "bankingapp2": "Create your (recurring) transfer to<br><br><b><ouribannumber></b>\n<b><ourname></b>\n<b><youruniquecode></b>",
            "saved": "Saved",
            "screenshot2": "We've added the screenshot to your Photo Library.",
            "screenshot3": "We couldn't save your screenshot. Try taking a screenshot manually.",
            "receivenotifications": "Receive notifications",
            "receivenotifications2": "To receive instant bitcoin payments, you must allow notifications.\n\nWithout notifications, you cannot receive payments to your wallet.",
            "receivenotifications3": "To receive instant bitcoin payments, you must allow notifications.\n\nOn your device, go to Settings > Notifications > bittr to authorize our notifications.\n\nYou're free to continue without notifications, but then all your purchases will be paid into the regular (on-chain) part of your wallet.",
            "lightningneedsnotifications": "Lightning payouts are delivered via push notifications, so you must allow notifications to switch to lightning.\n\nOn your device, go to Settings > Notifications > bittr to authorize our notifications, then try again.",
            "verificationfail": "Please enter the correct verification code.",
            "bittrsignupfail": "Something went wrong creating your account. Please try again.",
            "bittrsignupfail2": "The IBAN you've entered appears to be invalid. Please enter a valid IBAN.",
            "bittrsignupfail3": "Something went wrong. Please try again later.",
            "bittrsignupfail4": "Something went wrong verifying your email address. Please try again.",
            "emailresent": "We've resent our email!",
            "emailresent2": "Check your Spam and Promotion folders to see if the code is there.\n\nPlease also check whether your address is correct:",
            "weresorry": "We're sorry!",
            "onlyiban": "Buying bitcoin with bittr is only available to IBAN holders.\n\nYou can still use your wallet to send and receive bitcoin.",
            "gotowallet": "Go to wallet",
            "fetchconversionrates": "Fetch conversion rates",
            "startlightningnode": "Start lightning node",
            "initiatewallet": "Initiate wallet",
            "syncwallet": "Sync wallet",
            "finalcalculations": "Final calculations",
            "payrequest": "Pay request",
            "payrequest1": "You can send <b>between <minsendable> and <maxsendable> satoshis</b>. Enter the amount of satoshis you'd like to pay.",
            "withdrawrequest": "Withdraw request",
            "withdrawrequest1": "You can withdraw between <minwithdrawable> and <maxwithdrawable> satoshis. How many satoshis would you like to withdraw?",
            "withdrawrequest3": "Are you sure you'd like to withdraw <withdrawable> satoshis?",
            "lnurlpayment": "Copy this invoice and go to Send to make your instant payment.",
            "lnurlfail1": "We could not complete this withdraw request. Error:",
            "lnurlfail2": "We could not complete your pay request. Error:",
            "lnurlscannerlabel": "Scan a QR code to perform an LNURL pay or withdraw request.",
            "lnurl": "LNURL status",
            "lnurlfail3": "We've received an error while handling this request. Please try again.",
            "lnurlfail4": "We currently only support LNURL pay and withdraw requests.",
            "sendvcscan": "Scan",
            "sendvcpaste": "Paste",
            "sendvctype": "Type",
            "language": "Language",
            "historicaldata": "We could not reach our server. Please try again.",
            "bitcoinvalue": "bitcoin value",
            "swapfunds": "swap funds",
            "swapfunds2": "Swap funds",
            "swapdirection": "I'd like to move my funds from...",
            "swapsubtitle": "Move satoshis between your bitcoin wallet and your bitcoin lightning connection.",
            "move": "Move",
            "onchaintolightning": "Onchain to Lightning",
            "lightningtoonchain": "Lightning to Onchain",
            "satsatatime": "Move up to <amount> sats.",
            "enteramountofsatoshis": "Enter amount of satoshis",
            "nodatareceived": "No data was received",
            "swapamountexceeded": "You can only move up to <amount> satoshis at a time. Please enter an amount within this limit.",
            "swapfunds3": "The expected fee to move <b><amount> satoshis</b> (<convertedamount>) is <b><feesamount> satoshis</b> (<convertedfees>).",
            "swapfunds3range": "The expected fee to move <b><amount> satoshis</b> (<convertedamount>) is between <b><feesamountmin> and <feesamount> satoshis</b> (<convertedfees>).",
            "onchaintolightningexplanation": "\n\nIt may take around <b>10 minutes</b> to complete this swap. You may close the app in the meantime.\n\nIf the swap fails, some of the paid fees may not be refundable.",
            "wishtoproceed": "Do you wish to proceed?",
            "proceed": "Proceed",
            "message": "message",
            "direction": "Direction",
            "fees": "Fees",
            "status": "Status",
            "swaperror1": "We could not initiate this swap.",
            "swaperror2": "We encountered some issue while processing your swap. No funds have been swapped. Please try again.",
            "swapstatuspreparing": "Preparing",
            "swapstatusawaitingconfirmation": "Waiting to be mined",
            "swapstatusawaitingpayment": "Awaiting payment",
            "swapstatusinvoicepending": "Awaiting swap payout",
            "swapstatusswapcomplete": "Swap complete",
            "swapstatusfailedtopay": "Swap failed (couldn't pay invoice)",
            "swapstatusexpired": "Swap expired",
            "swapstatusincorrectamount": "Swap failed (incorrect amount)",
            "swapstatusawaitingtransaction": "Awaiting transaction",
            "swapstatusinvoicexpired": "Swap failed (invoice expired)",
            "swapstatusfailed": "Swap failed",
            "both": "Both",
            "bothamountlabel": "Amount and description (optional)",
            "add": "Add",
            "insatoshis": "In satoshis",
            "addressandamount": "Address and amount",
            "invoiceandamount": "Invoice and amount",
            "amountmissing": "Please enter the amount of satoshis you'd like to send.",
            "forgotpin": "Forgot PIN",
            "forgotpin2": "Please enter your 12-word recovery phrase to reset your PIN.",
            "forgotpin3": "The recovery phrase is incorrect.",
            "reset": "Reset",
            "resetpin": "Reset PIN",
            "newaddress": "new address",
            "newaddress2": "Are you sure you wish to reveal a new address?\n\nThe best practice is to only reveal a new address once the previous one has been used.",
            "notificationsrequired": "Notifications Required",
            "notificationsrequiredmessage": "To process swaps, you need to be online. We'd like to notify you once your transaction is confirmed so that you can finalize the swap in the app. Please allow notification permissions.",
            "swapstatusupdate": "Your swap status has been updated",
            "invalidbitcoinaddress": "Invalid bitcoin address",
            "insufficientfunds": "Insufficient funds",
            "lightninginsufficientfunds": "You don't have enough instant bitcoin funds to send this payment. Your available balance is <b><amount> satoshis</b>.",
            "onchaininsufficientfunds": "You don't have enough onchain funds to send this payment. Your available onchain balance is <b><amount> satoshis</b>.",
            "swapinsufficientfunds": "However, you have enough regular bitcoin funds to swap and pay. Your available onchain balance is <b><amount> satoshis</b>.",
            "swapinsufficientfundslightning": "However, you have enough instant bitcoin funds to swap and pay. Your available instant balance is <b><amount> satoshis</b>.",
            "swapandpay": "Swap & Pay",
            "invalidinvoice": "Invalid Lightning invoice",
            "swapid": "Swap ID",
            "removewalletfromdevice": "Remove wallet",
            "removewallet1": "Are you sure you want to remove this wallet from your device?\n\nYou can restore the wallet using your recovery phrase.",
            "removalinprogress": "It looks like you started removing this wallet from your device, but it wasn't finished — a Lightning connection may still have been closing.\n\nWould you like to try removing it again?",
            "swapquestion": "Swap status",
            "swapquestionswapcreated0": "We've initiated the swap of your funds from onchain to lightning, but no funds have been moved yet.",
            "swapquestionswapcreated1": "We've initiated the swap of your funds from lightning to onchain, but no funds have been moved yet.",
            "swapquestiontransactionmempool0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nWe're currently waiting for your onchain transaction to be confirmed on the blockchain.",
            "swapquestiontransactionconfirmed0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning connection.",
            "swapquestioninvoicepending0": "In order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has now been confirmed, we're waiting to receive the swapped funds into your lightning connection.",
            "swapquestioninvoicefailedtopay0": "The swap of your funds from onchain to lightning could not be completed.\n\nIn order to swap your funds from onchain to lightning, we (1) perform an onchain transaction, then (2) wait for that transaction to be confirmed on the blockchain, and then (3) receive the funds in your lightning connection.\n\nThe onchain transaction has been paid and confirmed. However, the lightning invoice could not be paid. We're refunding the funds back into your onchain wallet.",
            "swapquestioncomplete0": "The swap of your funds from onchain to lightning has been completed.",
            "swapquestioncomplete1": "The swap of your funds from lightning to onchain has been completed.",
            "swapquestionexpired0": "The swap of your funds from onchain to lightning was not completed in time. If any funds were sent, they will be refunded into your onchain wallet.",
            "swapquestionexpired1": "The swap of your funds from lightning to onchain was not completed in time. If any funds were sent, they will be refunded into your lightning connection.",
            "swapquestiongeneric": "We're checking the current status of your swap.",
            "downloadswapfile": "Download details",
            "instantpayments": "Instant payments",
            "refundid": "Refund ID",
            "lightningid": "Lightning ID",
            "onchainid": "Onchain ID",
            "moved": "Moved",
            "from": "From",
            "swapstatus": "Swap status",
            "swapsucceeded": "Complete",
            "swappending": "Pending",
            "swapfailed": "Failed and refunded",
            "expecting": "Expecting",
            "note": "Note",
            "paymentrequestfailed": "Payment Request Failed",
            "paymentrequestfailed2": "We couldn't process this payment request. If this keeps happening, please contact support@getbittr.com.",
            "paymentrequest": "Payment Request",
            "paymentrequest2": "Someone wants to pay you <b><amount> satoshis</b>! Please sign in to accept the payment.",
            "paymentrequest3": "Someone wants to pay you <b><amount> satoshis</b>! Accept now or try again later in Device Details.",
            "handlenow": "Handle now",
            "notification": "Notification",
            "notificationhandlingfail": "We cannot handle the notification you've received, because it doesn't contain the data we expect.",
            "recipientRejected": "Recipient rejected",
            "userAbandoned": "User abandoned",
            "retriesExhausted": "Retries exhausted",
            "paymentExpired": "Payment expired",
            "routeNotFound": "Route not found",
            "unknownRequiredFeatures": "Unknown required features",
            "invoiceRequestExpired": "Invoice request expired",
            "invoiceRequestRejected": "Invoice request rejected",
            "blindedPathCreationFailed": "Blinded path creation failed",
            "generatinginvoice": "Generating invoice",
            "missingwords": "Missing words",
            "missingwords2": "Please enter all 3 words to confirm your recovery phrase. This helps ensure you have backed up your wallet correctly.",
            "invalidwords": "Invalid words",
            "invalidwords2": "Some of the words you entered are not valid recovery phrase words. Please check your backup and try again.",
            "incorrectphrase": "Incorrect recovery phrase",
            "incorrectphrase2": "Some of the words you've entered are incorrect. Please double-check your recovery phrase backup and try again.\n\nFor your security, we recommend taking a fresh backup of your recovery phrase to ensure you have the correct words.",
            "incompletephrase": "Incomplete Recovery Phrase",
            "incompletephrase2": "Please enter all 12 words of your recovery phrase to restore your wallet.",
            "restorewalleterror": "Unable to restore wallet. Please try again.",
            "invalidphrase": "Invalid Recovery Phrase",
            "invalidphrase2": "The recovery phrase you entered is not valid. Please double-check your backup and try again.\n\nFor your security, we recommend taking a fresh backup of your recovery phrase to ensure you have the correct words.",
            "handlinglnurl": "Handling LNURL",
            "newlightningconnection": "New Lightning connection",
            "newlightningconnection2": "You've successfully opened a lightning connection with bittr. You can now send and receive payments across the bitcoin lightning network.\n\nAny funds that have already been deposited will show up shortly.",
            "channelfullswaprecommendation": "Bittr recommends you to swap <amount> satoshis. Alternatively you can get this transaction paid out to your regular balance. Would you like to receive this payment regularly (within 4-24 hours) or swap and receive instantly?",
            "swapandreceiveinstantly": "Swap & Instant Receive",
            "receiveonchain": "Receive on-chain",
            "counterpartyForceClosed": "the counterparty force closed the connection.",
            "holderForceClosed": "you force closed the connection.",
            "legacyCooperativeClosure": "the connection was closed cooperatively (legacy).",
            "counterpartyInitiatedCooperativeClosure": "the connection was closed cooperatively (counterparty-iniated).",
            "locallyInitiatedCooperativeClosure": "the connection was closed cooperatively (locally).",
            "commitmentTxConfirmed": "the commitment transaction was confirmed.",
            "fundingTimedOut": "the funding of the connection timed out.",
            "disconnectedPeer": "a peer connection could not be established.",
            "outdatedChannelManager": "the channel manager was outdated.",
            "counterpartyCoopClosedUnfundedChannel": "the unfunded connection was cooperatively closed (counterparty-initiated).",
            "fundingBatchClosure": "the funding batch was closed.",
            "htlCsTimedOut": "the hashed timelock contracts timed out.",
            "peerFeerateTooLow": "the proposed fee rate was too low.",
            "locallyCoopClosedUnfundedChannel": "the connection was closed cooperatively (locally, unfunded channel).",
            "url": "Address",
            "transfer3Amount": "Amount",
            "transfer3AmountLabel": "You can buy up to 999 € worth of bitcoin per 30 days from bittr.",
            "transfer3Lightning": "Instant payments",
            "transfer3LightningLabel": "For purchases between 20 and 100 €, we create a lightning connection. With lightning, you can send and receive instant payments against low fees.\n\nThe setup of this connection incurs a one-time fee of 10 000 satoshis. This fee covers the mining fees for opening and closing the connection, plus the reservation of funds on our side of the connection.",
            "transfer3Connection": "Lightning connection",
            "transfer3ConnectionLabel": "Lightning funds exist only on this device. Don't delete this app before closing your lightning connection.",
            "transfer3DCA": "Dollar-cost-averaging",
            "transfer3DCALabel": "Easily stack up on bitcoin by setting up a recurring bank transfer, e.g. 50 € every Monday.",
            "SpendingPolicyRequired": "Spending policy is not compatible with this kind of keychain.",
            "Version0": "Version 0 error.",
            "Version1Csv": "Version 1 CSV error.",
            "LockTime": "Lock time error.",
            "RbfSequenceCsv": "Replace-By-Fee Sequence CSV error.",
            "FeeTooLow": "The selected fee rate is too low. The required minimum fee is <required>.",
            "NoUtxosSelected": "No UTXOs have been selected.",
            "OutputBelowDustLimit": "The created output is under the dust limit of <dustlimit> satoshis",
            "ChangePolicyDescriptor": "Change policy descriptor error.",
            "InsufficientFunds": "You have insufficient funds available to send this amount, taking into account the minimum fee required to make a transaction. Try sending <less> fewer satoshis.",
            "NoRecipients": "No recipient has been entered.",
            "MissingKeyOrigin": "No explicit key origin has been provided.",
            "UnknownUtxo": "The UTXO is unknown in the internal database.",
            "MissingNonWitnessUtxo": "Missing non witness UTXO error.",
            "PushBytesError": "Push Bytes error.",
            "LockTimeConversionError": "Lock time conversion error.",
            "TransactionNotFound": "Transaction not found.",
            "HeaderHeightNotFound": "Header height not found.",
            "HeaderHashNotFound": "Header hash not found.",
            "InvalidHttpHeaderName": "Invalid HTTP header name.",
            "InvalidHttpHeaderValue": "Invalid HTTP header value.",
            "RequestAlreadyConsumed": "Request already consumed.",
            "InvalidResponse": "Invalid response.",
            "academybeta": "Academy (beta)",
            "academyheader": "Learn everything about bitcoin and take control of your financial future. From basics to advanced topics, we've got you covered.",
            "buyvcupdatedetails": "Update details",
            "buyvcupdatedetails2": "Your partner details have changed. The above details have been updated.",
            "buyvcupdatedetails3": "Your partner details are up-to-date.",
            "buyvcupdatedetails4": "We could not fetch your partner details at this time.",
            "EsploraHttpResponse": "Could not fetch latest block height from Esplora.",
            "signupvc2": "Please confirm the above statements in order to proceed.",
            "transfer1vc": "Please enter your IBAN and email in order to proceed.",
            "transfer15vc": "Please enter the verification code in order to proceed.",
            "transfer15vc2": "Something went wrong verifying your code. Please restart the app and try again. (Error: <error>)",
            "lnurlbetween": "Amount must be between <min> and <max> satoshis.",
            "invalidinvoice2": "The following is not a valid invoice.\n\n<invoice>",
            "reminder": "Reminder",
            "reminderbody": "The funds in your lightning connection exist only on this device. Don't delete this app before closing the connection.",
            "awaitingbdksync": "To send a regular transaction, please wait a moment while we sync your wallet.",
            "onchainsyncfailedtitle": "Syncing issue",
            "onchainsyncfailed": "We ran into an issue syncing the on-chain part of your wallet. Please try again later.",
            "onchainsynctimedout": "Syncing the on-chain part of your wallet is taking longer than expected. Your wallet and funds are safe.\n\nPlease reopen the app to try again. Do not delete the app from your phone.",
            "transferfee": "Transfer fee",
            "bittrfee": "Bittr fee",
            "surcharge": "Surcharge",
            "transferfee1": "This is the first payout into your new lightning connection. For the setup of the connection, bittr incurs a one-time fee of 10 000 satoshis.\n\nThis fee covers the mining fees for opening and closing the connection, plus the reservation of funds on our side of the connection.\n\nFor any future payouts into this connection, there will be no additional mining fees.",
            "transferfee2": "You have paid the mining fees for opening and closing a lightning connection in advance. While you are connected, there will be no additional mining fees.",
            "transferfee3": "This fee does not go to bittr, but directly to the bitcoin miners. Due to the decentralized nature of the bitcoin network, miners have to be incentivized (partially with transaction fees) to keep the network secure.",
            "bittrfee1": "Bittr does not charge subscription fees or take a cut in your gains. We charge a fixed fee of 1.5% on incoming funds.",
            "surcharge1": "Bittr charges a € 1,00 surcharge for payments below € 100,00.",
            "receivedatbittr": "Received at bittr",
            "bittrpendingpayout": "Pending payout",
            "bittrpendingpayout2": "There are no pending payouts available at this time. If you need our help, please contact support@getbittr.com.",
            "bittrpendingpayout3": "There's a pending payout available for handling. Would you like to do so now?",
            "failedinvoicepayment1": "This invoice could not be paid, due to the following error:\n\n<message>",
            "exchangerate": "Exchange rate",
            "invoicecreatefail": "We could not create an invoice. Please try again later.",
            "10mins": "10 mins",
            "1hour": "1 hour",
            "1day": "1 day",
            "slow": "Slow",
            "scanner": "Scanner",
            "estimatedfees": "Estimated fees",
            "alertlightningfees": "Lightning fees",
            "alertlightningfees2": "The fees for this instant payment depend on the length of the route between your and the recipient's lightning connections - and the fees charged by intermediaries on that route.",
            "selectcurrency": "Currency",
            "selectcurrencymessage": "Choose your preferred currency.",
            "selectlanguage": "Language",
            "selectlanguagemessage": "Choose your preferred language.",
            "transactiontype": "Transaction type",
            "transactiontype2": "<b>Regular</b>\nGet an address, to receive regular on-chain transactions.\n\n<b>Instant</b>\nCreate an invoice, to receive instant payments into your lightning connection.\n\n<b>Both</b>\nCreate a Bitcoin QR, which contains an on-chain address as well as a lightning invoice.\n\n<b>URL</b>\nIf available, receive instant payments through your lightning URL.",
            "transactiontype3": "<b>Regular</b>\nEnter a bitcoin address, to send regular on-chain transactions.\n\n<b>Instant</b>\nEnter an invoice or lightning URL, to make instant bitcoin lightning payments.",
            "maximumonchain": "Your bittr wallet consists of a bitcoin wallet (for regular payments) and a bitcoin lightning connection (for instant payments).\n\nThe maximum amount you can send for regular payments, is your full regular balance minus the minimum required transaction fees.",
            "bitcoinqr": "Bitcoin QR",
            "unavailable": "Unavailable",
            "refresh": "Renew",
            "more": "More",
            "getaddress": "Address",
            "getbitcoinqr": "Bitcoin QR",
            "showlnurl": "Lightning address",
            "alertlnurl": "Lightning address",
            "receiveamount": "Add amount",
            "alertmessageonchain": "Share an address, to receive transactions into your wallet.\n\nTap Refresh to reveal additional addresses to your wallet.\n\nThe best practice is to do so only once the previous address has been used.",
            "alertmessagelightning": "Create a lightning invoice, to receive instant payments into your lightning connection.\n\nOptionally, you can add an amount and description to your invoice.",
            "alertmessagebitcoinqr": "Share a bitcoin QR, a universal standard for sharing a regular address and lightning invoice simultaneously.\n\nOptionally, you can add an amount and description to your bitcoin QR.",
            "alertmessagelnurl": "Share your lightning address, to receive instant payments into your lightning connection.\n\nThis address has been created for you as part of your sign-up with bittr.\n\nYou can receive emails to your lightning address. These will be forwarded to your own email address associated with your bittr account.",
            "receiveenteramount": "Enter amount",
            "receiveenterdescription": "Add a note",
            "selecttransactiontype": "Share a lightning URL or invoice, a bitcoin QR or address.",
            "noaddressavailable": "No new address is available at this time.\n\nFor proper performance, we reveal a maximum of ten unused addresses.\n\nMake sure to use an address before revealing a new one.",
            "paywithbitcoin": "Pay with bitcoin",
            "locationunavailable": "Your location details are unavailable to us.\n\nOn your device, go to <b>Settings > Apps > Bittr</b>, to check your location permissions.",
            "noplaces": "There seem to be no businesses in this area that accept bitcoin payments.",
            "placeserror": "We could not download map data at this time. Please try again later.",
            "poweredbyboltz": "Powered by",
            "boltzexplanation": "<b>Boltz.exchange</b> is a non-custodial bitcoin bridge. It enables you to swap funds between bitcoin layers, while staying in full control of your money.",
            "boltzexplanation2": "Go to Boltz",
            "boltzexplanation3": "Powered by Boltz",
            "openinmaps": "Open in Maps",
            "openinmaps2": "Select which app you prefer to open.",
            "openinmaps3": "Google Maps",
            "openinmaps4": "Maps",
            "lnauth1": "<domain> wants to <action> with your lightning wallet. No bitcoin will be sent. Would you like to proceed?",
            "lnauth2": "You've been successfully signed in.",
            "lnauth3": "We could not sign you in. Please try again.",
            "removewallet": "Remove wallet",
            "settings": "Settings",
            "buyvclightning": "Lightning",
            "buyvclightningexplanation": "Purchases up to 100 EUR/CHF go into your Lightning connection. Spend and receive instantly, with very low fees.\n\nTurn this off to receive your bittr purchases on-chain instead, in the regular part of your wallet.",
            "lightningnotready": "Lightning not ready",
            "paymentmodeupdateerror": "Couldn't update payout mode",
            "connectionclosed": "Connection closed",
            "pendingclosure": "Your lightning connection was recently closed. These funds (<pendingfunds> satoshis) will be deposited into your regular wallet.",
            "viewactiveconnection": "View active connection",
            "channelclosuretransaction": "These are the funds from your closed lightning connection, returning to your regular wallet."
            
        ]
        
        if let foundWord = allWords[withID] {
            return foundWord
        } else {
            return ""
        }
    }
    
}
