package com.bittr.android.core.designsystem

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.window.DialogProperties
import com.bittr.android.core.common.TestID

/**
 * One button on a [BittrAlert]. Position in the list is what numbers its test ID.
 *
 * [dismissesAlert] is what the back gesture does. Android users expect back to
 * close a dialog, and a dialog that ignores it feels broken — but *which* of the
 * buttons back is equivalent to is a per-alert answer. On the scanner's
 * permanently-denied alert, back means Cancel; it does not mean Settings.
 */
data class BittrAlertButton(
    val label: String,
    val dismissesAlert: Boolean = false,
    val onClick: () -> Unit,
)

/**
 * The app's alert, and the Android half of iOS's `AlertManager`.
 *
 * Two things here are load-bearing for the Maestro suite and are easy to lose in a
 * refactor:
 *
 * 1. **The button test IDs are applied here, by index.** `alert.button.0`,
 *    `alert.button.1`, … — generated by [TestID.Alert.buttonAt] from the button's
 *    position, exactly as `AlertManager.swift:178` does it on iOS. The flows assert
 *    on the numbered form, so the number has to come from the same rule on both
 *    platforms; `shared/test-ids/README.md` is explicit that hand-interpolating it
 *    at a call site is how one platform ends up 1-based and the other 0-based.
 *
 * 2. **Order is Cancel-first.** Position 0 is the way out. The approved copy
 *    specifies the pairs that way (*cancel* / *continue*, *cancel* / *settings*)
 *    and `send_onchain.yaml` taps `alert.button.0` to dismiss. Material would
 *    conventionally put the confirming action first; matching the flows matters
 *    more, and a suite that taps the wrong button fails several screens later in a
 *    way that reads like a different bug.
 *
 * The alert is intentionally plain Material 3 for now. iOS draws a rounded card
 * with an icon and a shadow (`AlertManager.swift:291-331`); reproducing that is
 * BIT-4's design-system work, and every call site reads through this function, so
 * it lands here without touching a screen.
 */
@Composable
fun BittrAlert(
    title: String,
    message: String,
    buttons: List<BittrAlertButton>,
    modifier: Modifier = Modifier,
) {
    require(buttons.isNotEmpty()) {
        "A BittrAlert with no buttons cannot be dismissed — it would trap the user on " +
            "the screen underneath it."
    }

    AlertDialog(
        onDismissRequest = {
            // Back / outside-tap resolves to whichever button says it is the way
            // out. If none does, the alert is a decision the user has to make and
            // back does nothing, which is the Material behaviour for that case.
            buttons.firstOrNull { it.dismissesAlert }?.onClick?.invoke()
        },
        properties = DialogProperties(
            dismissOnBackPress = buttons.any { it.dismissesAlert },
            dismissOnClickOutside = false,
        ),
        // Spelled out rather than left to Material's defaults. AlertDialog reaches
        // for `surfaceContainerHigh` and `onSurfaceVariant`, and [BittrTheme] does
        // not set either — so the default M3 baseline shows through and the alert
        // comes out lavender, in a brand-led app whose theme deliberately avoids
        // Material You for exactly that reason. These three read from the scheme
        // BIT-4 owns.
        containerColor = MaterialTheme.colorScheme.surface,
        titleContentColor = MaterialTheme.colorScheme.onSurface,
        textContentColor = MaterialTheme.colorScheme.onSurface,
        title = {
            Text(
                text = title,
                style = MaterialTheme.typography.headlineSmall,
                textAlign = TextAlign.Center,
                modifier = Modifier.fillMaxWidth(),
            )
        },
        text = {
            Text(
                text = message,
                style = MaterialTheme.typography.bodyMedium,
                textAlign = TextAlign.Center,
                modifier = Modifier.fillMaxWidth(),
            )
        },
        // Both buttons go in one full-width stack rather than into AlertDialog's
        // confirm/dismiss slots. Those slots lay out side by side and truncate, and
        // the approved labels ("Continue", "Settings") sit next to a body of three
        // lines — a stack is what iOS draws and what stays readable at large font
        // sizes.
        confirmButton = {
            Column(
                modifier = Modifier.fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(BittrTokens.Spacing.xs),
            ) {
                buttons.forEachIndexed { position, button ->
                    AlertButton(button = button, position = position)
                }
            }
        },
        modifier = modifier,
    )
}

/**
 * Position 0 is the way out and is drawn quieter; everything after it is an action.
 */
@Composable
private fun AlertButton(button: BittrAlertButton, position: Int) {
    val buttonModifier = Modifier
        .fillMaxWidth()
        .padding(vertical = BittrTokens.Spacing.xs)
        .testTag(TestID.Alert.buttonAt(position))

    if (position == 0 && button.dismissesAlert) {
        TextButton(onClick = button.onClick, modifier = buttonModifier) {
            Text(button.label)
        }
    } else {
        Button(onClick = button.onClick, modifier = buttonModifier) {
            Text(button.label)
        }
    }
}
